import ts from 'typescript';
import {readFileSync,writeFileSync,mkdirSync,readdirSync} from 'node:fs';
import {resolve,dirname,relative} from 'node:path';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
const root=resolve('.sites-runtime/prototype-tests');mkdirSync(root,{recursive:true});writeFileSync(resolve(root,'package.json'),'{"type":"commonjs"}');
for(const file of ['lib/launch.ts','lib/publication.ts','lib/public-venues.ts','app/api/public/[action]/route.ts','lib/venues.ts','lib/catering.ts','lib/catering-server.ts','app/api/catering/[action]/route.ts','lib/booking.ts','lib/owner-venue.ts','lib/db.ts','lib/demo-server.ts','lib/calendar.ts','app/api/demo/[action]/route.ts']){
 let source=readFileSync(file,'utf8').replace("import {env} from 'cloudflare:workers';",'const env=globalThis.__testEnv;');
 if(file==='lib/demo-server.ts')source=source.replace("import {getChatGPTUser,type ChatGPTUser} from '@/app/chatgpt-auth';",'type ChatGPTUser=any;async function getChatGPTUser(){return globalThis.__testUser;}');
 const dest=resolve(root,file.replace(/\.ts$/,'.js'));mkdirSync(dirname(dest),{recursive:true});
 source=source.replace(/(['"])@\//g,(_,quote)=>quote+(relative(dirname(dest),root)||'.')+'/');
 writeFileSync(dest,ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText);
}
const sql=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+file,'utf8'));
// The package migration changes the index without rewriting existing booking data.
const migrationDb=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')&&!f.startsWith('0003_')).sort())migrationDb.exec(readFileSync('drizzle/'+f,'utf8'));
migrationDb.prepare("INSERT INTO demo_slots (venue_slug,event_date,status,hold_id,quote_json) VALUES ('preserved','2026-01-01','booked','legacy-id','{}')").run();
migrationDb.exec(readFileSync('drizzle/0003_futuristic_magneto.sql','utf8'));
assert.equal(migrationDb.prepare('SELECT hold_id FROM demo_slots').get().hold_id,'legacy-id');
assert.equal(migrationDb.prepare("SELECT [unique] AS u FROM pragma_index_list('demo_slots') WHERE name='idx_demo_slot_venue_date'").get().u,0);migrationDb.close();
class Statement{constructor(text,args=[]){this.text=text;this.args=args;}bind(...args){return new Statement(this.text,args);}first(){return sql.prepare(this.text).all(...this.args)[0]||null;}all(){return {results:sql.prepare(this.text).all(...this.args)};}run(){const r=sql.prepare(this.text).run(...this.args);return {meta:{changes:Number(r.changes)}};}}
const objects=new Map();globalThis.__testEnv={RITEVENUE_MODE:'private_demo',RITEVENUE_ADMIN_EMAIL:'admin@example.test',DB:{prepare:text=>new Statement(text),batch:statements=>{sql.exec('BEGIN');try{const results=statements.map(s=>s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}},BUCKET:{put:async(k,b)=>objects.set(k,b),get:async k=>objects.has(k)?{body:objects.get(k)}:null,delete:async k=>objects.delete(k)}};
globalThis.__testUser={userId:'couple-a',email:'couple@example.test',displayName:'Test couple'};
globalThis.fetch=()=>{throw new Error('Unexpected external network call');};
const require=createRequire(resolve(root,'entry.js'));const api=require('./app/api/demo/[action]/route.js');const {venues,indiaToday}=require('./lib/venues.js');const domain=require('./lib/booking.js');
assert.equal(venues.length,20);assert.equal(new Set(venues.map(v=>v.slug)).size,20);assert.ok(venues.every(v=>v.city==='Bengaluru'));assert.equal(new Set(venues.map(v=>v.type)).size,5);
assert.match(indiaToday(),/^\d{4}-\d{2}-\d{2}$/);
const origin='https://ritevenue.test';
async function post(action,body,headers={}){return api.POST(new Request(origin+'/api/demo/'+action,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',...headers},body:JSON.stringify(body)}),{params:Promise.resolve({action})});}
async function get(action,query=''){return api.GET(new Request(origin+'/api/demo/'+action+query),{params:Promise.resolve({action})});}
const selection={venueSlug:venues[0].slug,date:indiaToday(),guests:100,packageId:'marriage-24h',addons:['suite']};
assert.equal((await post('hold',{...selection,total:1})).status,400);assert.equal((await post('hold',{...selection,date:'2026-02-30'})).status,400);assert.equal((await post('hold',{...selection,guests:9999})).status,400);assert.equal((await post('hold',selection,{Origin:'https://attacker.test'})).status,403);
const attempts=await Promise.all(Array.from({length:12},()=>post('hold',selection)));assert.equal(attempts.filter(r=>r.status===201).length,1);assert.equal(attempts.filter(r=>r.status===409).length,11);
const hold=await attempts.find(r=>r.status===201).json();assert.equal(hold.quote.advance+hold.quote.balance,hold.quote.total);assert.equal(hold.quote.items.reduce((s,i)=>s+i.amount,0)+hold.quote.tax,hold.quote.total);
const own=await (await get('calendar','?venue='+selection.venueSlug+'&month='+selection.date.slice(0,7))).json();assert.equal(own.days[0].ownHold.id,hold.id);
globalThis.__testUser={userId:'couple-b',email:'other@example.test'};const other=await (await get('calendar','?venue='+selection.venueSlug+'&month='+selection.date.slice(0,7))).json();assert.equal(other.days[0].ownHold,undefined);assert.ok(!JSON.stringify(other).includes('couple-a'));assert.equal((await post('confirm',{holdId:hold.id,acknowledgeDemo:true})).status,409);await post('release',{holdId:hold.id});assert.equal(sql.prepare('SELECT status FROM demo_slots').get().status,'held');assert.equal((await post('pricing',{venueSlug:selection.venueSlug,pricing:domain.defaultPricing(venues[0])})).status,403);
globalThis.__testUser={userId:'admin',email:'admin@example.test'};const updated={...domain.defaultPricing(venues[0]),rent:9999900};assert.equal((await post('pricing',{venueSlug:selection.venueSlug,pricing:updated})).status,200);
globalThis.__testUser={userId:'couple-a',email:'couple@example.test'};const confirmed=await (await post('confirm',{holdId:hold.id,acknowledgeDemo:true})).json();const repeated=await (await post('confirm',{holdId:hold.id,acknowledgeDemo:true})).json();assert.equal(repeated.id,confirmed.id);assert.equal(sql.prepare('SELECT count(*) AS n FROM demo_bookings').get().n,1);assert.equal(sql.prepare('SELECT status FROM demo_slots').get().status,'booked');assert.equal(JSON.parse(sql.prepare('SELECT quote_json FROM demo_bookings').get().quote_json).total,hold.quote.total);assert.equal((await post('hold',selection)).status,409);
const next={...selection,venueSlug:venues[1].slug};const expired=await (await post('hold',next)).json();sql.prepare('UPDATE demo_slots SET expires_at=0 WHERE hold_id=?').run(expired.id);assert.equal((await post('confirm',{holdId:expired.id,acknowledgeDemo:true})).status,409);const reclaimed=await (await post('hold',next)).json();assert.ok(reclaimed.id);await post('release',{holdId:reclaimed.id});assert.equal((await post('hold',next)).status,201);
const id=crypto.randomUUID();const draft={id,name:'Owner test venue',locality:'Jayanagar',address:'Private test address in Bengaluru',type:'Wedding hall',capacity:200,description:'Owner-provided demonstration description with sufficient detail for review.',pricing:updated,images:[],rightsConfirmed:true,submit:false};assert.equal((await post('drafts',draft)).status,200);assert.equal((await post('drafts',{...draft,submit:true})).status,400);
const fake=new Request(origin+'/api/demo/images',{method:'POST',headers:{Origin:origin,'Content-Type':'image/jpeg'},body:'not an image'});assert.equal((await api.POST(fake,{params:Promise.resolve({action:'images'})})).status,400);
// Fixture bytes exercise upload validation/storage; no real image or external call is needed.
const bytes=new Uint8Array([255,216,255,224,0,0,0,0,0,0,0,0,0]);const upload=await api.POST(new Request(origin+'/api/demo/images',{method:'POST',headers:{Origin:origin,'Content-Type':'image/jpeg'},body:bytes}),{params:Promise.resolve({action:'images'})});assert.equal(upload.status,201);const image=await upload.json();assert.equal((await post('drafts',{...draft,images:[image.id],submit:true})).status,200);
globalThis.__testUser={userId:'couple-b',email:'other@example.test'};assert.equal((await post('drafts',draft)).status,403);assert.equal((await get('image','?id='+image.id)).status,404);assert.equal((await get('admin')).status,403);assert.equal((await (await get('drafts')).json()).drafts.length,0);
assert.equal((await (await get('catalog')).json()).venues.length,20);
assert.equal((await get('calendar','?venue=owner-'+id+'&month='+indiaToday().slice(0,7))).status,404);
assert.equal((await post('hold',{...selection,venueSlug:'owner-'+id})).status,404);
assert.equal((await post('review',{id,status:'approved_for_demo',note:'Not the admin',expectedUpdatedAt:'stale'})).status,403);
globalThis.__testUser={userId:'admin',email:'admin@example.test'};assert.equal((await get('image','?id='+image.id)).status,200);assert.equal((await post('review',{id,status:'approved_for_demo',note:'Reviewed for private demo only.',expectedUpdatedAt:sql.prepare('SELECT updated_at FROM owner_drafts WHERE id=?').get(id).updated_at})).status,200);assert.equal(sql.prepare('SELECT status FROM owner_drafts WHERE id=?').get(id).status,'approved_for_demo');
// Approval publishes one searchable listing with owner pricing and scoped photos.
const revision=sql.prepare('SELECT updated_at FROM owner_drafts WHERE id=?').get(id).updated_at;
assert.equal((await post('review',{id,status:'approved_for_demo',note:'Repeat review is stale',expectedUpdatedAt:revision})).status,409);
globalThis.__testUser={userId:'couple-b',email:'other@example.test'};
const published=await (await get('catalog')).json();
assert.equal(published.venues.length,21);
const ownerVenue=published.venues.find(v=>v.slug==='owner-'+id);
assert.equal(ownerVenue.name,draft.name);assert.equal(ownerVenue.area,draft.locality);
assert.equal(ownerVenue.source,'owner');assert.equal(ownerVenue.images[0],'/api/demo/image?id='+image.id);
assert.deepEqual(published.pricing[ownerVenue.slug],updated);
assert.ok(!JSON.stringify(published).includes('owner_id'));
assert.equal((await get('image','?id='+image.id)).status,200);
const ownerSelection={...selection,venueSlug:ownerVenue.slug};
const ownerHold=await (await post('hold',ownerSelection)).json();
assert.ok(ownerHold.id);assert.equal(ownerHold.quote.venueSource,'owner');
assert.equal(ownerHold.quote.items[0].amount,updated.marriageRent);
assert.equal((await post('hold',ownerSelection)).status,409);
const visibleCalendar=await (await get('calendar','?venue='+ownerVenue.slug+'&month='+indiaToday().slice(0,7))).json();
assert.equal(visibleCalendar.days[0].status,'held');
// Saving an edit removes the listing and its public-to-signed-in photo access.
const priorPayload=sql.prepare('SELECT data_json FROM owner_drafts WHERE id=?').get(id).data_json;
globalThis.__testUser={userId:'couple-a',email:'couple@example.test'};
const amended={...draft,images:[image.id],name:'Updated owner venue',pricing:{...updated,rent:1234500},submit:true};
assert.equal((await post('drafts',amended)).status,200);
assert.equal((await (await get('catalog')).json()).venues.length,20);
const raced=sql.prepare(domain.ownerHoldSQL).get(...domain.holdBindings(ownerVenue.slug,domain.lastBookableDate(),crypto.randomUUID(),'couple-b',Math.floor(Date.now()/1000)+7200,ownerHold.quote,Math.floor(Date.now()/1000),{id,dataJson:priorPayload}));
assert.equal(raced,undefined);
globalThis.__testUser={userId:'couple-b',email:'other@example.test'};
assert.equal((await get('image','?id='+image.id)).status,404);
assert.equal((await post('hold',{...ownerSelection,date:domain.lastBookableDate()})).status,404);
// The customer's existing hold can complete without changing its saved quote.
const ownerConfirmed=await (await post('confirm',{holdId:ownerHold.id,acknowledgeDemo:true})).json();
assert.ok(ownerConfirmed.id);
assert.equal(JSON.parse(sql.prepare('SELECT quote_json FROM demo_bookings WHERE id=?').get(ownerConfirmed.id).quote_json).total,ownerHold.quote.total);
globalThis.__testUser={userId:'admin',email:'admin@example.test'};
assert.equal((await post('review',{id,status:'approved_for_demo',note:'Stale review must not publish',expectedUpdatedAt:'old-revision'})).status,409);
const freshRevision=sql.prepare('SELECT updated_at FROM owner_drafts WHERE id=?').get(id).updated_at;
assert.equal((await post('review',{id,status:'approved_for_demo',note:'Approved revised listing',expectedUpdatedAt:freshRevision})).status,200);
const republished=await (await get('catalog')).json();
assert.equal(republished.venues.filter(v=>v.slug===ownerVenue.slug).length,1);
assert.equal(republished.venues.find(v=>v.slug===ownerVenue.slug).name,amended.name);
assert.equal(republished.pricing[ownerVenue.slug].rent,1234500);
assert.equal((await (await get('calendar','?venue='+ownerVenue.slug+'&month='+indiaToday().slice(0,7))).json()).days[0].status,'booked');
// Native form checkout is independent of client hydration and uses the same transaction logic.
async function formPost(action,data){return api.POST(new Request(origin+'/api/demo/'+action,{method:'POST',headers:{Origin:origin,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(data)}),{params:Promise.resolve({action})});}
globalThis.__testUser={userId:'couple-a',email:'couple@example.test'};
const formStart=await formPost('start-checkout',{venueSlug:venues[4].slug,date:indiaToday(),guests:'120',packageId:'full-day',addons:''});assert.equal(formStart.status,303);const formHold=new URL(formStart.headers.get('location')).pathname.split('/').pop();assert.match(formHold,/^[a-f0-9-]{36}$/);
const formConfirm=await formPost('complete-checkout',{holdId:formHold,acknowledgeDemo:'yes'});assert.equal(formConfirm.status,303);assert.ok(new URL(formConfirm.headers.get('location')).pathname.startsWith('/bookings/'));assert.equal((await formPost('complete-checkout',{holdId:formHold,acknowledgeDemo:'yes'})).headers.get('location'),formConfirm.headers.get('location'));
const invalidForm=await formPost('start-checkout',{venueSlug:venues[4].slug,date:'invalid',guests:'120',packageId:'full-day',addons:''});assert.equal(invalidForm.status,303);assert.ok(invalidForm.headers.get('location').includes('invalid_input'));
// Four independently priced packages, 5% advance, and extra hours.
assert.equal(hold.quote.advancePercent,5);assert.equal(hold.quote.advance,Math.round(hold.quote.total*0.05));
assert.equal(hold.quote.startsAt,selection.date+'T16:00:00+05:30');
assert.equal(hold.quote.endsAt,domain.shiftDate(selection.date,1)+'T16:00:00+05:30');
const rounded=domain.makeQuote(venues[8],domain.pricingSchema.parse({rent:10001,ac:0,generator:0,parking:0,cleaning:0}),{...selection,packageId:'full-day',extraHours:0,addons:[]});
assert.equal(rounded.advance,590);assert.equal(rounded.advance+rounded.balance,rounded.total);
assert.equal(domain.shiftDate('2028-02-28',1),'2028-02-29');
const priceSet=domain.pricingSchema.parse({rent:4000000,marriageRent:5000000,morningRent:2000000,eveningRent:2500000,extraHour:300000,ac:0,generator:0,parking:0,cleaning:0});
for(const [packageId,start,end,rent] of [['marriage-24h',16,40,5000000],['full-day',8,22,4000000],['half-morning',7,14,2000000],['half-evening',16,23,2500000]]){
 const q=domain.makeQuote(venues[8],priceSet,{...selection,packageId,extraHours:2,addons:[]});
 assert.equal(q.items[0].amount,rent);assert.equal(q.items.find(i=>i.label.startsWith('Extra hours')).amount,600000);
 assert.equal(q.startsAt,selection.date+'T'+String(start).padStart(2,'0')+':00:00+05:30');
 assert.equal(q.endsAt,domain.shiftDate(selection.date,Math.floor((end+2)/24))+'T'+String((end+2)%24).padStart(2,'0')+':00:00+05:30');
 assert.equal(q.advance,Math.round(q.total*0.05));assert.equal(q.balance,q.total-q.advance);
}
const testDate=domain.shiftDate(indiaToday(),5),nextDate=domain.shiftDate(testDate,1);
const overnight={...selection,venueSlug:venues[8].slug,date:testDate,extraHours:0,addons:[]};
const overnightHold=await (await post('hold',overnight)).json();assert.ok(overnightHold.id);
const nextMorning={...overnight,date:nextDate,packageId:'half-morning'};
assert.equal((await post('hold',nextMorning)).status,409);
const nextCalendar=await (await get('calendar','?venue='+venues[8].slug+'&month='+nextDate.slice(0,7)+'&package=half-morning')).json();
assert.equal(nextCalendar.days.find(d=>d.date===nextDate).status,'held');assert.equal(nextCalendar.days.find(d=>d.date===nextDate).ownHold,undefined);
assert.equal((await post('hold',{...overnight,date:nextDate})).status,201); // Back-to-back 4 PM access is allowed.
// Two half-days can be sold on one date. Extra hours block only true overlaps.
const morning={...overnight,venueSlug:venues[9].slug,packageId:'half-morning'};
const morningHold=await (await post('hold',morning)).json();assert.ok(morningHold.id);
const evening={...morning,packageId:'half-evening'};
const eveningHold=await (await post('hold',evening)).json();assert.ok(eveningHold.id);
assert.equal((await post('hold',{...morning,extraHours:3})).status,409);
const morningConfirmation=await (await post('confirm',{holdId:morningHold.id,acknowledgeDemo:true})).json();
const eveningConfirmation=await (await post('confirm',{holdId:eveningHold.id,acknowledgeDemo:true})).json();
assert.ok(morningConfirmation.id);assert.ok(eveningConfirmation.id);assert.notEqual(morningConfirmation.id,eveningConfirmation.id);
assert.equal(sql.prepare("SELECT count(*) n FROM demo_slots WHERE venue_slug=? AND event_date=? AND status='booked'").get(venues[9].slug,testDate).n,2);
const extendedMorning={...morning,venueSlug:venues[10].slug,extraHours:3};const extendedHold=await (await post('hold',extendedMorning)).json();assert.ok(extendedHold.id);
assert.equal((await post('hold',{...evening,venueSlug:venues[10].slug})).status,409);
assert.equal((await (await get('calendar','?venue='+venues[10].slug+'&month='+testDate.slice(0,7)+'&package=half-evening')).json()).days.find(d=>d.date===testDate).status,'held');
sql.prepare('UPDATE demo_slots SET expires_at=0 WHERE hold_id=?').run(extendedHold.id);
assert.equal((await post('hold',{...evening,venueSlug:venues[10].slug})).status,201);
// Reading availability includes the selected extra hours.
const reverseEvening=await (await post('hold',{...evening,venueSlug:venues[11].slug})).json();assert.ok(reverseEvening.id);
assert.equal((await (await get('calendar','?venue='+venues[11].slug+'&month='+testDate.slice(0,7)+'&package=half-morning&extraHours=0')).json()).days.some(d=>d.date===testDate),false);
assert.equal((await (await get('calendar','?venue='+venues[11].slug+'&month='+testDate.slice(0,7)+'&package=half-morning&extraHours=3')).json()).days.find(d=>d.date===testDate).status,'held');
assert.equal((await post('hold',{...morning,venueSlug:venues[11].slug,extraHours:3})).status,409);
// Different start dates compete atomically for overlapping access.
const adjacentAttempts=await Promise.all([post('hold',{...overnight,venueSlug:venues[12].slug}),post('hold',{...nextMorning,venueSlug:venues[12].slug})]);
assert.equal(adjacentAttempts.filter(r=>r.status===201).length,1);assert.equal(adjacentAttempts.filter(r=>r.status===409).length,1);
const boundary=new Date(indiaToday()+'T00:00:00Z');boundary.setUTCMonth(boundary.getUTCMonth()+1,1);const firstNextMonth=boundary.toISOString().slice(0,10),lastThisMonth=domain.shiftDate(firstNextMonth,-1);
assert.equal((await post('hold',{...overnight,venueSlug:venues[13].slug,date:lastThisMonth,extraHours:4})).status,201);
assert.equal((await (await get('calendar','?venue='+venues[13].slug+'&month='+firstNextMonth.slice(0,7)+'&package=half-evening')).json()).days.find(d=>d.date===firstNextMonth).status,'held');
assert.ok((await (await get('calendar','?date='+firstNextMonth)).json()).unavailable.includes(venues[13].slug));
// Existing locked quotes retain original same-day hours and 25% advances.
const legacy={...domain.makeQuote(venues[14],domain.defaultPricing(venues[14]),{...overnight,venueSlug:venues[14].slug,packageId:'full-day'}),hours:'08:00 - 22:00',packageName:'Full day'};
delete legacy.advancePercent;delete legacy.startsAt;delete legacy.endsAt;delete legacy.extraHours;legacy.advance=Math.round(legacy.total/4);legacy.balance=legacy.total-legacy.advance;
const legacyId=crypto.randomUUID();sql.prepare("INSERT INTO demo_slots (venue_slug,event_date,status,hold_id,user_id,expires_at,quote_json) VALUES (?,?,'held',?,'couple-a',?,?)").run(venues[14].slug,testDate,legacyId,Math.floor(Date.now()/1000)+7200,JSON.stringify(legacy));
assert.equal((await post('hold',{...overnight,venueSlug:venues[14].slug,date:domain.shiftDate(testDate,-1)})).status,409);
assert.equal((await post('hold',{...nextMorning,venueSlug:venues[14].slug})).status,201);
const legacyConfirmation=await (await post('confirm',{holdId:legacyId,acknowledgeDemo:true})).json();
const savedLegacy=JSON.parse(sql.prepare('SELECT quote_json FROM demo_bookings WHERE id=?').get(legacyConfirmation.id).quote_json);
assert.equal(savedLegacy.advance,legacy.advance);assert.equal(savedLegacy.hours,'08:00 - 22:00');assert.equal(savedLegacy.advancePercent,undefined);
assert.equal((await get('calendar','?date='+testDate+'&package=invalid')).status,400);
assert.equal((await post('hold',{...morning,extraHours:-1})).status,400);assert.equal((await post('hold',{...morning,extraHours:5})).status,400);
assert.equal((await post('hold',{...morning,extraHours:1.5})).status,400);assert.equal((await post('hold',{...morning,extraHour:1})).status,400);
globalThis.__testUser=null;assert.equal((await get('calendar','?date='+indiaToday())).status,401);assert.equal((await post('hold',selection)).status,401);
// Catering discovery, estimate integrity and supplier moderation.
const catering=require('./lib/catering.js'),cateringAPI=require('./app/api/catering/[action]/route.js');
async function cpost(action,body,headers={}){return cateringAPI.POST(new Request(origin+'/api/catering/'+action,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',...headers},body:JSON.stringify(body)}),{params:Promise.resolve({action})});}
async function cget(action){return cateringAPI.GET(new Request(origin+'/api/catering/'+action),{params:Promise.resolve({action})});}
assert.equal((await cget('catalog')).status,401);
assert.equal((await cpost('estimate',{})).status,401);
globalThis.__testUser={userId:'couple-a',email:'couple@example.test'};
const cat=await (await cget('catalog')).json();assert.equal(cat.suppliers.length,3);
assert.equal(cat.venues.find(v=>v.slug===ownerVenue.slug).policy.mode,'unconfirmed');
const external=cat.venues.find(v=>v.policy.mode==='external_allowed'),hotel=cat.venues.find(v=>v.policy.mode==='in_house'),restricted=cat.venues.find(v=>v.policy.mode==='approved_only');
const sample=cat.suppliers[0],menu=sample.menus[0];
const cs={venueSlug:external.slug,supplierId:sample.id,menuId:menu.id,date:domain.shiftDate(indiaToday(),10),guests:50,optional:false};
const er=await cpost('estimate',cs);assert.equal(er.status,200);const estimate=(await er.json()).estimate;
assert.equal(estimate.billedGuests,100);assert.equal(estimate.items[0].amount,6500000);
assert.equal(estimate.subtotal,8100000);assert.equal(estimate.tax,405000);assert.equal(estimate.total,8505000);assert.equal(estimate.reserved,false);
assert.equal(estimate.advance,undefined);assert.equal(estimate.guestChangeDeadline,domain.shiftDate(cs.date,-7));
const optionalEstimate=(await (await cpost('estimate',{...cs,optional:true})).json()).estimate;assert.equal(optionalEstimate.total-estimate.total,1260000);
const hotelEstimate=(await (await cpost('estimate',{...cs,venueSlug:hotel.slug,supplierId:cat.suppliers[2].id,menuId:cat.suppliers[2].menus[0].id})).json()).estimate;
assert.equal(hotelEstimate.items.find(i=>i.label==='Minimum food-spend adjustment').amount,0);
const topup=catering.cateringEstimate(sample,menu,{...external.policy,minimumFoodSpend:10000000},cs);assert.equal(topup.items[1].amount,3500000);
assert.equal(catering.cateringEstimate(sample,{...menu,perPlate:10001,taxBps:333,minimumGuests:1,staffing:0,equipment:0,transport:0},{...external.policy,venueFee:0},{...cs,guests:3}).tax,999);
assert.equal((await cpost('estimate',{...cs,total:1})).status,400);
assert.equal((await cpost('estimate',{...cs,guests:0})).status,400);
assert.equal((await cpost('estimate',{...cs,guests:1.5})).status,400);
assert.equal((await cpost('estimate',{...cs,date:'2026-02-30'})).status,400);
assert.equal((await cpost('estimate',{...cs,venueSlug:hotel.slug})).status,409);
assert.equal((await cpost('estimate',{...cs,venueSlug:ownerVenue.slug})).status,409);
assert.equal((await cpost('estimate',{...cs,venueSlug:restricted.slug,supplierId:cat.suppliers[1].id,menuId:cat.suppliers[1].menus[0].id})).status,409);
assert.equal((await cpost('estimate',{...cs,supplierId:cat.suppliers[1].id,menuId:cat.suppliers[1].menus[0].id,date:domain.shiftDate(indiaToday(),7)})).status,409);
assert.equal((await cpost('estimate',cs,{Origin:'https://attacker.test'})).status,403);
assert.equal((await cpost('reserve',cs)).status,404);
assert.ok(catering.supplierCompatibility(external.policy,{...sample,serviceAreas:['Unknown locality']},external.area,cs.date,100));
assert.ok(catering.supplierCompatibility(external.policy,sample,external.area,cs.date,sample.maxGuests+1));
assert.ok(catering.supplierCompatibility(external.policy,sample,external.area,cs.date,0));
assert.ok(catering.supplierCompatibility(external.policy,sample,external.area,domain.shiftDate(indiaToday(),366),100));
assert.ok(catering.supplierCompatibility(external.policy,{...sample,availableTo:indiaToday()},external.area,cs.date,100));
const supplierId=crypto.randomUUID();const supplier={id:supplierId,name:'Test catering business',description:'Owner submitted catering service description for the private review workflow.',contactEmail:'private-supplier@example.test',phone:'9999999999',serviceAreas:[external.area],maxGuests:300,availableFrom:indiaToday(),availableTo:domain.shiftDate(indiaToday(),90),unavailableDates:[],menus:[{...menu,id:'owner-menu'}],images:[],rightsConfirmed:true,submit:false};
assert.equal((await cpost('drafts',{data:supplier,expectedRevision:null})).status,200);
const supplierRevision=()=>sql.prepare('SELECT revision FROM catering_drafts WHERE id=?').get(supplierId).revision;
const initialRevision=supplierRevision();
assert.equal((await cpost('drafts',{data:supplier,expectedRevision:null})).status,409);
assert.equal((await cpost('drafts',{data:{...supplier,submit:true},expectedRevision:initialRevision})).status,400);
const cateringUpload=await api.POST(new Request(origin+'/api/demo/images',{method:'POST',headers:{Origin:origin,'Content-Type':'image/jpeg'},body:bytes}),{params:Promise.resolve({action:'images'})});
assert.equal(cateringUpload.status,201);const cateringPhoto=(await cateringUpload.json()).id;
const submittedSupplier={...supplier,images:[cateringPhoto],submit:true};
assert.equal((await cpost('drafts',{data:submittedSupplier,expectedRevision:initialRevision})).status,200);
assert.notEqual(supplierRevision(),initialRevision);
assert.equal((await cpost('drafts',{data:submittedSupplier,expectedRevision:initialRevision})).status,409);
globalThis.__testUser={userId:'couple-b',email:'other@example.test'};
assert.equal((await cpost('drafts',{data:submittedSupplier,expectedRevision:supplierRevision()})).status,403);
assert.equal((await cpost('drafts',{data:{...submittedSupplier,id:crypto.randomUUID()},expectedRevision:null})).status,400);
assert.equal((await get('image','?id='+cateringPhoto)).status,404);
assert.equal((await cget('admin')).status,403);assert.equal((await (await cget('drafts')).json()).drafts.length,0);
const reviewData={id:supplierId,status:'approved_for_demo',note:'Menu and photos reviewed for private catalog.',expectedRevision:supplierRevision()};
assert.equal((await cpost('review',reviewData)).status,403);
globalThis.__testUser={userId:'admin',email:'admin@example.test'};
assert.equal((await cpost('review',{...reviewData,expectedRevision:initialRevision})).status,409);
assert.equal((await cpost('review',reviewData)).status,200);
assert.equal((await cpost('review',reviewData)).status,409);
globalThis.__testUser={userId:'couple-b',email:'other@example.test'};
const approvedCatalog=await (await cget('catalog')).json();assert.equal(approvedCatalog.suppliers.length,4);
assert.ok(!JSON.stringify(approvedCatalog).includes('private-supplier@example.test'));assert.ok(!JSON.stringify(approvedCatalog).includes('9999999999'));
assert.equal((await get('image','?id='+cateringPhoto)).status,200);
assert.equal((await cpost('estimate',{...cs,supplierId,menuId:'owner-menu'})).status,200);
globalThis.__testUser={userId:'couple-a',email:'couple@example.test'};
assert.equal((await cpost('drafts',{data:{...submittedSupplier,name:'Updated supplier business'},expectedRevision:supplierRevision()})).status,200);
assert.equal((await (await cget('catalog')).json()).suppliers.length,3);
globalThis.__testUser={userId:'couple-b',email:'other@example.test'};
assert.equal((await get('image','?id='+cateringPhoto)).status,404);
assert.equal((await cpost('estimate',{...cs,supplierId,menuId:'owner-menu'})).status,404);
// Optional catering is attached only to an active owned venue hold.
globalThis.__testUser={userId:'couple-a',email:'couple@example.test'};
const attachDate=domain.shiftDate(indiaToday(),30);
const attachmentHold=await (await post('hold',{...selection,venueSlug:external.slug,date:attachDate,guests:100})).json();
assert.ok(attachmentHold.id);
const heldQuote=()=>JSON.parse(sql.prepare('SELECT quote_json FROM demo_slots WHERE hold_id=?').get(attachmentHold.id).quote_json);
const attachSelection={...cs,venueSlug:external.slug,date:attachDate,guests:100};
const attachment={holdId:attachmentHold.id,expectedRevision:null,selection:attachSelection};
assert.equal((await cpost('attach',{...attachment,total:1})).status,400);
assert.equal((await cpost('attach',attachment,{Origin:'https://attacker.test'})).status,403);
globalThis.__testUser={userId:'couple-b',email:'other@example.test'};
assert.equal((await cpost('attach',attachment)).status,409);
globalThis.__testUser={userId:'couple-a',email:'couple@example.test'};
assert.equal((await cpost('attach',{...attachment,selection:{...attachSelection,venueSlug:hotel.slug}})).status,400);
assert.equal((await cpost('attach',{...attachment,selection:{...attachSelection,guests:101}})).status,400);
assert.equal((await cpost('attach',{...attachment,selection:{...attachSelection,date:domain.shiftDate(attachDate,2)}})).status,400);
assert.equal((await cpost('attach',attachment)).status,200);
const firstAttachment=heldQuote();
assert.equal(firstAttachment.cateringEstimate.supplierId,attachSelection.supplierId);
assert.equal(firstAttachment.cateringEstimate.reserved,false);
for(const field of ['total','advance','balance','startsAt','endsAt'])assert.equal(firstAttachment[field],attachmentHold.quote[field]);
assert.deepEqual(firstAttachment.items,attachmentHold.quote.items);
assert.equal((await cpost('attach',attachment)).status,409); // stale second tab
const remove={holdId:attachmentHold.id,expectedRevision:firstAttachment.cateringRevision,selection:null};
assert.equal((await cpost('attach',remove)).status,200);
assert.equal(heldQuote().cateringEstimate,undefined);
assert.equal((await cpost('attach',remove)).status,409);
const secondDay={...attachSelection,date:domain.shiftDate(attachDate,1)};
assert.equal((await cpost('attach',{...attachment,expectedRevision:heldQuote().cateringRevision,selection:secondDay})).status,200);
assert.equal(heldQuote().cateringEstimate.date,secondDay.date);
const beforeConfirmation=heldQuote();
const cateringBooking=await (await post('confirm',{holdId:attachmentHold.id,acknowledgeDemo:true})).json();
assert.ok(cateringBooking.id);
const storedCateringQuote=JSON.parse(sql.prepare('SELECT quote_json FROM demo_bookings WHERE id=?').get(cateringBooking.id).quote_json);
assert.deepEqual(storedCateringQuote.cateringEstimate,beforeConfirmation.cateringEstimate);
assert.equal(storedCateringQuote.advance,attachmentHold.quote.advance);
assert.equal((await cpost('attach',{...attachment,expectedRevision:beforeConfirmation.cateringRevision,selection:null})).status,409);
assert.equal((await (await post('confirm',{holdId:attachmentHold.id,acknowledgeDemo:true})).json()).id,cateringBooking.id);
const expiring=await (await post('hold',{...selection,venueSlug:external.slug,date:domain.shiftDate(attachDate,3)})).json();
sql.prepare('UPDATE demo_slots SET expires_at=0 WHERE hold_id=?').run(expiring.id);
assert.equal((await cpost('attach',{...attachment,holdId:expiring.id})).status,409);
const skipped=await (await post('hold',{...selection,venueSlug:external.slug,date:domain.shiftDate(attachDate,5)})).json();
const skippedBooking=await (await post('confirm',{holdId:skipped.id,acknowledgeDemo:true})).json();
assert.equal(JSON.parse(sql.prepare('SELECT quote_json FROM demo_bookings WHERE id=?').get(skippedBooking.id).quote_json).cateringEstimate,undefined);
console.log('Passed optional catering: owned active holds, add/remove, stale edits, venue/date/guest matching, overnight meal dates, confirmation snapshot, unchanged venue advance, expired/confirmed holds and venue-only checkout.');
console.log('Passed catering: policy compatibility, supplier dates/localities/capacity, minimum billing/spend, optional charges, integer-paise rounding, tamper/origin validation, private contacts/photos, draft ownership, stale edit/review rejection, approval visibility and edit withdrawal. No reservation or advance created.');
console.log('Passed: 20 venues, pricing integrity, input validation, competing holds, expiry/reclaim, idempotent confirmation, immutable quotes, cross-account isolation, admin restrictions, private uploads, 5% advance, four package prices, half-day bookings, extra-hour overlap prevention, legacy quote preservation, approval-to-catalog, owner venue booking, edit withdrawal, stale review protection and draft moderation. No external calls made.');

// Public launch is the default when no private-demo test setting is supplied.
delete globalThis.__testEnv.RITEVENUE_MODE;
const publicAPI=require('./app/api/public/[action]/route.js');
const {publicDateStatus}=require('./lib/publication.js');
async function pget(action,query=''){return publicAPI.GET(new Request(origin+'/api/public/'+action+query),{params:Promise.resolve({action})});}
globalThis.__testUser=null;
assert.equal((await pget('catalog')).status,200);
assert.equal((await (await pget('catalog')).json()).venues.length,0);
assert.equal((await pget('image','?id='+image.id)).status,404);
assert.equal((await pget('calendar','?venue='+venues[0].slug)).status,404);
assert.equal((await get('drafts')).status,401);
globalThis.__testUser={userId:'couple-b',email:'other@example.test'};
assert.equal((await get('catalog')).status,403);
assert.equal((await get('calendar','?venue='+venues[0].slug+'&month='+indiaToday().slice(0,7))).status,403);
assert.equal((await get('image','?id='+image.id)).status,404);
assert.equal((await cget('catalog')).status,403);
for(const action of ['hold','confirm','release','start-checkout','complete-checkout','cancel-checkout'])assert.equal((await post(action,selection)).status,410);
for(const action of ['estimate','attach'])assert.equal((await cpost(action,cs)).status,410);
globalThis.__testUser={userId:'couple-a',email:'couple@example.test'};
const publicId=crypto.randomUUID(),calendarFrom=indiaToday(),calendarTo=domain.shiftDate(indiaToday(),30),unavailableDate=domain.shiftDate(indiaToday(),3);
const publicDraft={...draft,id:publicId,name:'Owner-authorized test hall',images:[image.id],submit:true,publication:{consent:false,calendar:{from:calendarFrom,to:calendarTo,unavailable:[unavailableDate]}}};
assert.equal((await post('drafts',publicDraft)).status,200);
const publicRevision=()=>sql.prepare('SELECT updated_at FROM owner_drafts WHERE id=?').get(publicId).updated_at;
globalThis.__testUser={userId:'admin',email:'admin@example.test'};
assert.equal((await post('review',{id:publicId,status:'approved_public',note:'Cannot publish without owner consent',expectedUpdatedAt:publicRevision()})).status,400);
globalThis.__testUser={userId:'couple-a',email:'couple@example.test'};
const consented={...publicDraft,publication:{...publicDraft.publication,consent:true}};
assert.equal((await post('drafts',consented)).status,200);
assert.equal((await (await pget('catalog')).json()).venues.length,0);
globalThis.__testUser={userId:'couple-b',email:'other@example.test'};
assert.equal((await post('review',{id:publicId,status:'approved_public',note:'Wrong account cannot publish',expectedUpdatedAt:publicRevision()})).status,403);
globalThis.__testUser={userId:'admin',email:'admin@example.test'};
assert.equal((await post('review',{id:publicId,status:'approved_public',note:'Owner permission and listing reviewed',expectedUpdatedAt:publicRevision()})).status,200);
globalThis.__testUser=null;
const publicCatalog=await (await pget('catalog')).json();
assert.equal(publicCatalog.venues.length,1);assert.equal(publicCatalog.venues[0].name,consented.name);
assert.ok(!JSON.stringify(publicCatalog).includes('review_note'));assert.ok(!JSON.stringify(publicCatalog).includes('owner_id'));
assert.equal((await pget('image','?id='+image.id)).status,200);
assert.equal((await pget('image','?id='+cateringPhoto)).status,404);
const publicCalendar=(await (await pget('calendar','?venue=owner-'+publicId)).json());
assert.equal(publicDateStatus(publicCalendar.calendar,unavailableDate,publicCalendar.updatedAt),'unavailable');
assert.equal(publicDateStatus(publicCalendar.calendar,domain.shiftDate(indiaToday(),1),publicCalendar.updatedAt),'available');
assert.equal(publicDateStatus(publicCalendar.calendar,domain.shiftDate(calendarTo,1),publicCalendar.updatedAt),'unconfirmed');
assert.equal(publicDateStatus(publicCalendar.calendar,indiaToday(),new Date(Date.now()-8*86400000).toISOString()),'unconfirmed');
assert.equal(publicDateStatus(publicCalendar.calendar,indiaToday(),''),'unconfirmed');
assert.equal(publicDateStatus(null,indiaToday(),publicCalendar.updatedAt),'unconfirmed');
globalThis.__testUser={userId:'couple-b',email:'other@example.test'};
const calendarChange={id:publicId,calendar:{from:calendarFrom,to:calendarTo,unavailable:[]},expectedUpdatedAt:publicRevision()};
assert.equal((await post('public-calendar',calendarChange)).status,409);
globalThis.__testUser={userId:'couple-a',email:'couple@example.test'};
assert.equal((await post('public-calendar',{...calendarChange,calendar:{...calendarChange.calendar,unavailable:['not-a-date']}})).status,400);
assert.equal((await post('public-calendar',calendarChange)).status,200);
assert.equal((await (await pget('catalog')).json()).venues.length,1);
assert.equal((await (await pget('calendar','?venue=owner-'+publicId)).json()).calendar.unavailable.length,0);
assert.equal((await post('public-calendar',{...calendarChange,expectedUpdatedAt:'stale'})).status,409);
assert.equal((await post('drafts',{...consented,publication:{...consented.publication,consent:false},submit:false})).status,200);
globalThis.__testUser=null;
assert.equal((await (await pget('catalog')).json()).venues.length,0);
assert.equal((await pget('image','?id='+image.id)).status,404);
assert.equal((await pget('calendar','?venue=owner-'+publicId)).status,404);
console.log('Passed public launch: anonymous directory, explicit consent and admin approval, no demo inventory, scoped photos, private-record isolation, disabled transactions, owner calendar updates, stale/unconfirmed dates, and consent withdrawal.');
