import {notFound} from 'next/navigation';
import {z} from 'zod';
import {requireChatGPTUser} from '@/app/chatgpt-auth';
import {db} from '@/lib/db';
import {money} from '@/lib/venues';
import type {Quote} from '@/lib/booking';
import QuoteBreakdown from '@/components/quote-breakdown';
import CheckoutCatering from '@/components/checkout-catering';
export const dynamic='force-dynamic';
export const metadata={title:'Complete your demo booking',robots:{index:false,follow:false}};
export default async function Checkout({params,searchParams}:{params:Promise<{holdId:string}>;searchParams:Promise<{code?:string}>}){const {holdId}=await params;if(holdId==='problem'){const {code}=await searchParams;return <main className="content-page narrow"><h1>Let’s try that checkout again.</h1><p>{code==='not_available'?'The hold expired or the date is no longer available. Choose another available date.':code==='invalid_input'?'Check the date, guest count and demo acknowledgement before continuing.':'The checkout service could not complete the request. Check My bookings before retrying.'}</p><div className="workspace-actions"><a href="/" className="primary">Choose a venue & date</a><a href="/bookings" className="filter-button">My bookings</a></div></main>;}if(!z.string().uuid().safeParse(holdId).success)notFound();return <PrivateCheckout id={holdId}/>;}
async function PrivateCheckout({id}:{id:string}){const user=await requireChatGPTUser('/checkout/'+id);const database=db();const booking=await database.prepare('SELECT id FROM demo_bookings WHERE hold_id=? AND user_id=?').bind(id,user.userId).first<{id:string}>();if(booking)return <main className="content-page narrow"><h1>Your demo booking is already confirmed.</h1><p>Your date and locked quote are saved. You do not need to complete checkout again.</p><div className="workspace-actions"><a href="/" className="primary">Back to venues</a><a href={'/bookings/'+booking.id} className="filter-button">View confirmation</a><a href="/bookings" className="filter-button">My bookings</a></div></main>;const row=await database.prepare("SELECT venue_slug,expires_at,quote_json FROM demo_slots WHERE hold_id=? AND user_id=? AND status='held'").bind(id,user.userId).first<{venue_slug:string;expires_at:number;quote_json:string}>();if(!row||row.expires_at<=Math.floor(Date.now()/1000))return <main className="content-page narrow"><h1>This hold has expired.</h1><p>No demo booking was confirmed. Choose an available date to start a new checkout.</p><a href={row?'/venues/'+row.venue_slug+'#book':'/'} className="primary">Choose another date</a></main>;const quote:Quote=JSON.parse(row.quote_json);return <main className="content-page checkout-page"><p className="eyebrow">SELF-SERVE DEMO CHECKOUT</p><h1>Confirm your date.</h1><div className="hold-banner">Held until {new Date(row.expires_at*1000).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</div><h2>{quote.venueName}</h2><p>{quote.date} · {quote.packageName} · {quote.guests} guests</p><CheckoutCatering holdId={id} quote={quote}/><section id="venue-confirmation"><h2>Review & confirm your venue booking</h2><QuoteBreakdown quote={quote}/><div className="notice">Food and catering charges are separate from this venue quote. <a href={'/venues/'+quote.venueSlug}>Review the venue’s catering policy</a> before confirming. Returning to the venue does not release your hold.</div><form action="/api/demo/complete-checkout" method="post"><input type="hidden" name="holdId" value={id}/><label className="addon-option"><input type="checkbox" required name="acknowledgeDemo" value="yes"/><span>I understand this is a simulated advance and demo booking. No real payment is collected.</span></label><button className="primary" type="submit">Simulate advance & confirm · {money(quote.advance/100)}</button></form><form action="/api/demo/cancel-checkout" method="post"><input type="hidden" name="holdId" value={id}/><button className="filter-button" type="submit">Cancel checkout & release date</button></form><p className="muted">Your exact quote is saved on confirmation. The remaining balance is illustrative and no funds are payable for this demo.</p></section></main>;}
