'use client';
import {useState,type FormEvent} from 'react';

export default function AdminSignIn({returnTo}:{returnTo:string}){
 const [email,setEmail]=useState(''),[challengeId,setChallengeId]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function requestCode(event:FormEvent){event.preventDefault();setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/auth/request-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const result=await response.json() as {challengeId?:string;error?:string};if(!response.ok||!result.challengeId)throw new Error(result.error||'Could not send the code.');setChallengeId(result.challengeId);setNotice('If this is the configured administrator address, a six-digit code has been sent.');}catch(e){setError(e instanceof Error?e.message:'Could not send the code.');}finally{setBusy(false);}}
 async function verifyCode(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/auth/verify-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({challengeId,code})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Could not verify the code.');window.location.assign(returnTo);}catch(e){setError(e instanceof Error?e.message:'Could not verify the code.');}finally{setBusy(false);}}
 return <section className="catalog-connect"><div><p className="eyebrow">SECURE ADMIN ACCESS</p><h1>Sign in to RiteVenue.</h1><p>We’ll email a one-time code to the configured administrator address. Codes expire after 10 minutes.</p></div>{!challengeId?<form className="stack-form" onSubmit={requestCode}><label>Administrator email<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Sending…':'Email sign-in code'}</button></form>:<form className="stack-form" onSubmit={verifyCode}><label>Six-digit code<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))}/></label><button className="primary" disabled={busy||code.length!==6}>{busy?'Checking…':'Sign in'}</button><button className="filter-button" type="button" disabled={busy} onClick={()=>{setChallengeId('');setCode('');setNotice('');setError('');}}>Use another email</button></form>}{notice&&<p className="notice" role="status">{notice}</p>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
