'use client';
import {useState,useEffect,useMemo} from 'react';
import {Utensils,Users,MapPin,CalendarDays,Download,RefreshCw} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {money} from '@/lib/venues';
import {shiftDate} from '@/lib/booking';
import {supplierCompatibility,policyLabels,type CateringEstimate} from '@/lib/catering';
import type {CateringCatalog} from '@/lib/catering-server';
import {cateringApi} from '@/lib/catering-client';
export default function CateringExplorer({initialCatalog,initialVenue,initialDate,initialGuests,today,booking}:{booking?:{holdId:string;revision:string|null;startsOn:string;endsOn:string};initialCatalog:CateringCatalog;initialVenue:string;initialDate:string;initialGuests:number;today:string}){
 const [catalog,setCatalog]=useState(initialCatalog),[venueSlug,setVenue]=useState(initialVenue||(booking?'':initialCatalog.venues[0]?.slug)||''),[date,setDate]=useState(initialDate||today),[guests,setGuests]=useState(initialGuests||100),[diet,setDiet]=useState('all'),[budget,setBudget]=useState(''),[selected,setSelected]=useState(''),[optional,setOptional]=useState(false),[estimate,setEstimate]=useState<CateringEstimate|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const venue=catalog.venues.find(v=>v.slug===venueSlug);
 const matches=useMemo(()=>venue&&Number.isInteger(guests)&&guests>=1&&guests<=venue.capacity?catalog.suppliers.filter(s=>!supplierCompatibility(venue.policy,s,venue.area,date,guests)).flatMap(s=>s.menus.filter(m=>diet==='all'||m.diet===diet).map(menu=>({supplier:s,menu,key:s.id+':'+menu.id}))):[],[catalog,venue,date,guests,diet]);
 const choice=matches.find(m=>m.key===selected);
 useEffect(()=>{setEstimate(null);setError('');setOptional(false);},[venueSlug,date,guests,diet,selected]);
 useEffect(()=>{setEstimate(null);},[optional]);
 async function refresh(){setBusy(true);setError('');try{setCatalog(await cateringApi<CateringCatalog>('catalog'));setEstimate(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function calculate(){if(!venue||!choice)return;setBusy(true);setError('');setEstimate(null);try{const result=await cateringApi<{estimate:CateringEstimate}>('estimate',{venueSlug,supplierId:choice.supplier.id,menuId:choice.menu.id,date,guests,optional});setEstimate(result.estimate);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function attach(){if(!booking||!choice||!estimate)return;setBusy(true);setError('');try{await cateringApi('attach',{holdId:booking.holdId,expectedRevision:booking.revision,selection:{venueSlug,supplierId:choice.supplier.id,menuId:choice.menu.id,date,guests,optional}});window.location.assign('/checkout/'+booking.holdId+'#venue-confirmation');}catch(e){setError((e as Error).message);setBusy(false);}}
 function download(){if(!estimate)return;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({...estimate,notice:'Estimate only. No catering reservation, payment or price lock.'},null,2)],{type:'application/json'}));a.href=url;a.download='RiteVenue-catering-estimate.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><div className="catering-heading"><div><p className="eyebrow">RITEVENUE / CATERING PILOT</p>{booking?<h3>Choose a menu for your venue booking</h3>:<h1>A menu that fits your venue.</h1>}<p className="workspace-intro">Compare permitted caterers, menus and the full cost for one meal service.</p></div>{!booking&&<a className="filter-button" href="/caterer">Caterer workspace</a>}</div>
 <fieldset disabled={busy} className="catering-controls"><label>Venue<select disabled={!!booking} value={venueSlug} onChange={e=>{setVenue(e.target.value);setSelected('');}}>{catalog.venues.map(v=><option key={v.slug} value={v.slug}>{v.name} · {v.area}</option>)}</select></label><label>Meal service date<input type="date" required min={booking?.startsOn||today} max={booking?.endsOn||shiftDate(today,365)} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Expected guests<input disabled={!!booking} type="number" min="1" max={venue?.capacity||2000} value={guests||''} onChange={e=>setGuests(Number(e.target.value))}/></label><label>Menu preference<select value={diet} onChange={e=>setDiet(e.target.value)}><option value="all">All menus</option><option value="vegetarian">Vegetarian</option><option value="non_vegetarian">Non-vegetarian</option></select></label><label>Total budget (₹, optional)<input type="number" min="0" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="Compare against your total"/></label></fieldset>
 {venue&&<div className="catering-policy"><Utensils size={24}/><div><strong>{policyLabels[venue.policy.mode]}</strong><p>{venue.policy.notes||'The venue operator must confirm catering permissions and charges before a real event.'}</p><p>Venue catering fee: {money(venue.policy.venueFee/100)} · Minimum food spend: {money(venue.policy.minimumFoodSpend/100)}. Catering is priced separately from venue rental.</p><a href={'/venues/'+venue.slug}>View venue and booking calendar</a></div></div>}
 <div className="notice">Private discovery and pricing prototype. Dates are supplier-listed availability, not guaranteed capacity. Selecting a menu creates no reservation. Catering payments and advance terms are not enabled.</div>
 <div className="section-title"><h2>{matches.length} compatible menu packages</h2><button className="filter-button" disabled={busy} onClick={refresh}><RefreshCw size={16}/>Refresh suppliers</button></div>
 {(!Number.isInteger(guests)||guests<1||guests>(venue?.capacity||2000))&&<p className="error">Enter a valid guest count within the venue’s capacity.</p>}
 {!matches.length?<div className="empty-state"><h2>No compatible packages for this selection</h2><p>{venue?.policy.mode==='unconfirmed'?'This venue has not confirmed its catering rules yet.':'Try a different date, guest count or menu preference. Unlisted suppliers are not automatically permitted.'}</p></div>:<div className="catering-grid">{matches.map(({supplier:s,menu:m,key})=><article className={'catering-card '+(key===selected?'selected':'')} key={key}><img src={s.images[0]} alt={s.source==='sample'?'Illustrative dining setup, not this caterer’s food':s.name+' supplied photo'} width="640" height="300" loading="lazy"/><div className="catering-card-body"><span className="tag">{s.source==='sample'?'Fictional demo supplier':'Reviewed for private catalog'}</span><h2>{m.name}</h2><p className="supplier-name">{s.name}</p><p><MapPin size={16}/>{s.serviceAreas.join(', ')}</p><p><Users size={16}/>Minimum billed {m.minimumGuests} · Up to {s.maxGuests} guests</p><p>{m.diet==='vegetarian'?'Vegetarian':'Non-vegetarian'} · {m.serviceStyle.replaceAll('_',' ')}</p><p className="menu-dishes">{m.dishes}</p><div className="catering-card-bottom"><span><strong>{money(m.perPlate/100)}</strong> / plate<small>Mandatory charges and tax are additional below</small></span><button className="filter-button" aria-pressed={selected===key} disabled={busy} onClick={()=>{setSelected(key);setTimeout(()=>document.getElementById('catering-quote')?.scrollIntoView({behavior:'smooth',block:'start'}),50);}}>{selected===key?'Selected':'Compare full cost'}</button></div></div></article>)}</div>}
 {choice&&venue&&<section className="catering-quote" id="catering-quote"><div><p className="eyebrow">YOUR SELECTED PACKAGE</p><h2>{choice.menu.name}</h2><p>{choice.supplier.name} · {date} · {guests} expected guests</p><h3>What is included</h3><p>{choice.menu.inclusions}</p><p>{choice.supplier.description}</p><div className="draft-photos">{choice.supplier.images.slice(1).map(src=><img key={src} src={src} alt={choice.supplier.name+' supplied photo'} width="160" height="120"/>)}</div><p><strong>Guest-count deadline:</strong> {shiftDate(date||today,-choice.menu.guestChangeDeadlineDays)}. Extra guests after the agreed deadline: {money(choice.menu.extraGuestRate/100)} each, subject to supplier capacity and approval.</p><p><strong>Cancellation terms:</strong> {choice.menu.cancellationTerms}</p>{choice.menu.optionalPerGuest>0&&<label className="addon-option"><Checkbox disabled={busy} checked={optional} onCheckedChange={v=>setOptional(v===true)}/><span>{choice.menu.optionalName} · {money(choice.menu.optionalPerGuest/100)} per billable guest</span></label>}<button className="primary" disabled={busy||guests<1||guests>venue.capacity} onClick={calculate}>{busy?'Checking package…':'Calculate full catering cost'}</button><p className="muted">Catering is separate from your venue booking. No 5% catering advance is assumed.</p></div><div className="catering-total">{estimate?<><span className="tag">Estimate only · Not reserved</span><h3>Complete catering estimate</h3><p>{estimate.guests} expected · {estimate.billedGuests} billable guests</p>{estimate.items.map((i,n)=><div className="quote-line" key={n}><span>{i.label}</span><strong>{money(i.amount/100)}</strong></div>)}<div className="quote-line"><span>Tax ({estimate.taxBps/100}%, supplier-entered / illustrative)</span><strong>{money(estimate.tax/100)}</strong></div><div className="quote-line total"><span>Catering total</span><strong>{money(estimate.total/100)}</strong></div>{budget!==''&&Number(budget)>0&&<p className={estimate.total<=Number(budget)*100?'notice':'error'}>{estimate.total<=Number(budget)*100?'Within your catering budget':'Above your catering budget by '+money((estimate.total-Number(budget)*100)/100)}</p>}<p className="muted">One meal service. Venue rent is excluded. Guest-count, menu or service changes require a new estimate.</p><button className="filter-button" disabled={busy} onClick={download}><Download size={17}/>Download estimate</button>{booking&&<button className="primary" disabled={busy} onClick={attach}>Add menu estimate & continue</button>}</>:<div className="empty-state"><CalendarDays size={30}/><h3>See every charge</h3><p>Calculate to check the current package and venue policy. No catering is booked or paid.</p></div>}</div></section>}{error&&<div className="error" role="alert">{error}</div>}</>;
}
