'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {Checkbox} from '@/components/ui/checkbox';
import {cateringApi} from '@/lib/catering-client';
import {supplierSchema,type SupplierDraft,type CateringMenu} from '@/lib/catering';
import {indiaToday,money} from '@/lib/venues';
import {shiftDate} from '@/lib/booking';
type Editable=Omit<SupplierDraft,'rightsConfirmed'>&{rightsConfirmed:boolean};
type Row={id:string;data:SupplierDraft;status:string;review_note:string;revision:string};
const newMenu=():CateringMenu=>({id:crypto.randomUUID(),name:'',diet:'vegetarian',serviceStyle:'buffet',dishes:'',inclusions:'',perPlate:0,minimumGuests:100,staffing:0,equipment:0,transport:0,taxBps:0,extraGuestRate:0,guestChangeDeadlineDays:7,optionalName:'',optionalPerGuest:0,cancellationTerms:''});
const blank=():Editable=>({id:crypto.randomUUID(),name:'',description:'',contactEmail:'',phone:'',serviceAreas:['All Bengaluru'],maxGuests:500,availableFrom:indiaToday(),availableTo:shiftDate(indiaToday(),90),unavailableDates:[],menus:[newMenu()],images:[],rightsConfirmed:false,submit:false});
const amounts=[['perPlate','Food per plate'],['staffing','Mandatory service staff'],['equipment','Mandatory equipment & crockery'],['transport','Mandatory transport'],['extraGuestRate','Additional guest rate'],['optionalPerGuest','Optional add-on per billable guest']] as const;
export default function CatererWorkspace({adminView=false}:{adminView?:boolean}){
 const [rows,setRows]=useState<Row[]>([]),[draft,setDraft]=useState<Editable|null>(null),[revision,setRevision]=useState<string|null>(null),[areas,setAreas]=useState(''),[blocked,setBlocked]=useState(''),[notes,setNotes]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const refresh=useCallback(async()=>{const data=await cateringApi<{drafts:Row[]}>(adminView?'admin':'drafts');setRows(data.drafts);setReady(true);},[adminView]);
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[refresh]);
 function edit(d:Editable,r:string|null){setDraft(structuredClone(d));setRevision(r);setAreas(d.serviceAreas.join(', '));setBlocked(d.unavailableDates.join(', '));setError('');setNotice(r?'Saving edits removes the approved listing until it is reviewed again.':'');}
 const list=(value:string)=>Array.from(new Set(value.split(/[,\n]/).map(s=>s.trim()).filter(Boolean)));
 async function save(submit:boolean){if(!draft)return;setError('');setNotice('');const parsed=supplierSchema.safeParse({...draft,serviceAreas:list(areas),unavailableDates:list(blocked),submit});if(!parsed.success){setError(parsed.error.issues.map(i=>`${i.path.join(' › ')}: ${i.message}`).slice(0,4).join('. '));return;}setBusy(true);try{await cateringApi('drafts',{data:parsed.data,expectedRevision:revision});setDraft(null);setNotice(submit?'Submitted for admin review. Approval makes this supplier visible in the private catering catalog.':'Draft saved privately. Submit it for review when ready.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(files:FileList|null){if(!draft||!files)return;if(draft.images.length+files.length>6){setError('Use up to 6 photos.');return;}setBusy(true);setError('');try{for(const file of Array.from(files)){if(file.size>4*1024*1024)throw new Error('Each photo must be under 4 MB.');const r=await fetch('/api/demo/images',{method:'POST',headers:{'Content-Type':file.type},body:file});const data=await r.json() as {id:string;error?:string};if(!r.ok)throw new Error(data.error||'Photo upload failed.');setDraft(d=>d?{...d,images:[...d.images,data.id]}:d);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function review(row:Row,status:string){setBusy(true);setError('');setNotice('');try{await cateringApi('review',{id:row.id,status,note:notes[row.id]||'',expectedRevision:row.revision});setNotice(status==='approved_for_demo'?'Approved for private discovery. Matching venues can now show this caterer.':'Changes requested. The supplier remains hidden.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function updateMenu(index:number,patch:Partial<CateringMenu>){setDraft(d=>d?{...d,menus:d.menus.map((m,i)=>i===index?{...m,...patch}:m)}:d);}
 return <><div className="workspace-actions">{!adminView&&<button className="primary" disabled={busy} onClick={()=>edit(blank(),null)}>Add catering business</button>}<button className="filter-button" disabled={busy} onClick={()=>refresh().catch(e=>setError(e.message))}>Refresh list</button><Link className="filter-button" href="/catering">Browse catering</Link>{adminView&&<Link className="filter-button" href="/admin">Venue admin</Link>}</div>{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}
 {draft&&!adminView&&<form className="owner-editor stack-form" onSubmit={e=>{e.preventDefault();save(true);}}><fieldset disabled={busy} className="catering-fieldset stack-form"><div className="section-title"><h2>Catering business & menus</h2><button className="filter-button" type="button" onClick={()=>setDraft(null)}>Close editor</button></div><div className="form-grid"><label>Business name<input required minLength={3} maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Maximum guests per event<input required type="number" min={1} max={2000} value={draft.maxGuests} onChange={e=>setDraft({...draft,maxGuests:Number(e.target.value)})}/></label><label>Contact email (private)<input required type="email" value={draft.contactEmail} onChange={e=>setDraft({...draft,contactEmail:e.target.value})}/></label><label>Phone (private)<input required minLength={7} maxLength={30} value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label></div><label>About your catering service<textarea required minLength={30} maxLength={2000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Service localities, separated by commas<input required value={areas} onChange={e=>setAreas(e.target.value)}/></label><p className="muted">Use the venue locality spelling, such as Jayanagar, or “All Bengaluru” if you cover the whole city.</p><div className="form-grid"><label>Availability starts<input required type="date" value={draft.availableFrom} onChange={e=>setDraft({...draft,availableFrom:e.target.value})}/></label><label>Availability ends<input required type="date" min={draft.availableFrom} value={draft.availableTo} onChange={e=>setDraft({...draft,availableTo:e.target.value})}/></label></div><label>Unavailable dates (YYYY-MM-DD, separated by commas)<textarea value={blocked} onChange={e=>setBlocked(e.target.value)} placeholder="2026-12-10, 2026-12-11"/></label><p className="muted">Dates describe your stated capacity for discovery. They do not create live reservations. Updating them requires a new admin review.</p>
 {draft.menus.map((m,index)=><section className="catering-menu-editor stack-form" key={m.id}><div className="section-title"><h3>Menu {index+1}</h3>{draft.menus.length>1&&<button type="button" className="filter-button" onClick={()=>setDraft({...draft,menus:draft.menus.filter(x=>x.id!==m.id)})}>Remove menu</button>}</div><label>Package name<input required minLength={3} maxLength={80} value={m.name} onChange={e=>updateMenu(index,{name:e.target.value})}/></label><div className="form-grid"><label>Food preference<select value={m.diet} onChange={e=>updateMenu(index,{diet:e.target.value as CateringMenu['diet']})}><option value="vegetarian">Vegetarian</option><option value="non_vegetarian">Non-vegetarian / mixed</option></select></label><label>Service style<select value={m.serviceStyle} onChange={e=>updateMenu(index,{serviceStyle:e.target.value as CateringMenu['serviceStyle']})}><option value="buffet">Buffet</option><option value="served">Served at table</option><option value="banana_leaf">Banana leaf</option></select></label></div><label>Dishes included<textarea required minLength={10} maxLength={1000} value={m.dishes} onChange={e=>updateMenu(index,{dishes:e.target.value})}/></label><label>Service inclusions & exclusions<textarea required minLength={10} maxLength={800} value={m.inclusions} onChange={e=>updateMenu(index,{inclusions:e.target.value})}/></label><div className="pricing-fields">{amounts.map(([key,label])=><label key={key}>{label} (₹)<input type="number" required min={key==='perPlate'?1:0} max={1000000} step="0.01" value={m[key]/100} onChange={e=>updateMenu(index,{[key]:Math.round(Number(e.target.value)*100)})}/></label>)}<label>Minimum billable guests<input required type="number" min={1} max={draft.maxGuests} value={m.minimumGuests} onChange={e=>updateMenu(index,{minimumGuests:Number(e.target.value)})}/></label><label>Tax on estimate subtotal (%)<input required type="number" min={0} max={100} step="0.01" value={m.taxBps/100} onChange={e=>updateMenu(index,{taxBps:Math.round(Number(e.target.value)*100)})}/></label><label>Final guest count due (days before event)<input required type="number" min={0} max={60} value={m.guestChangeDeadlineDays} onChange={e=>updateMenu(index,{guestChangeDeadlineDays:Number(e.target.value)})}/></label></div><label>Optional add-on name<input maxLength={80} value={m.optionalName} onChange={e=>updateMenu(index,{optionalName:e.target.value})}/></label><label>Cancellation & change terms<textarea required minLength={10} maxLength={800} value={m.cancellationTerms} onChange={e=>updateMenu(index,{cancellationTerms:e.target.value})}/></label><p className="muted">Enter every mandatory charge. Zero means included. The prototype applies your tax rate to the whole catering subtotal, including venue fees; admin must review this estimate assumption before any real launch. Additional guests and later changes are excluded from the current estimate.</p></section>)}
 <button className="filter-button" type="button" disabled={draft.menus.length>=6} onClick={()=>setDraft({...draft,menus:[...draft.menus,newMenu()]})}>Add another menu</button><label className="addon-option"><Checkbox checked={draft.rightsConfirmed} onCheckedChange={v=>setDraft({...draft,rightsConfirmed:v===true})}/><span>I am authorized to submit these business details, prices and photos for review and display in the private prototype.</span></label><label className="upload-control">Upload food or event photos<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={!draft.rightsConfirmed} onChange={e=>{upload(e.target.files);e.target.value='';}}/></label><p className="muted">Up to 6 photos, 4 MB each. At least one photo is required for submission.</p><div className="draft-photos">{draft.images.map(id=><div key={id}><img src={'/api/demo/image?id='+id} alt="Supplier uploaded photo" width={160} height={120}/><button className="filter-button" type="button" onClick={()=>setDraft({...draft,images:draft.images.filter(i=>i!==id)})}>Remove</button></div>)}</div><div className="workspace-actions"><button className="filter-button" type="button" disabled={!draft.rightsConfirmed} onClick={()=>save(false)}>Save private draft</button><button className="primary" disabled={!draft.rightsConfirmed}>{busy?'Working…':'Submit for review'}</button></div></fieldset></form>}
 {!ready?<p role="status">Loading catering workspace…</p>:!rows.length?<div className="empty-state"><h2>{adminView?'No catering submissions yet':'Create your first catering menu'}</h2><p>Business details, menus, prices and photos are reviewed before appearing in private discovery.</p></div>:<div className="draft-list">{rows.map(row=><article key={row.id} className="draft-item"><div className="section-title"><div><span className="tag">{row.status.replaceAll('_',' ')}</span><h2>{row.data.name}</h2></div>{!adminView&&<button className="filter-button" disabled={busy} onClick={()=>edit(row.data,row.revision)}>Edit supplier</button>}</div><p>{row.data.description}</p><p>{row.data.serviceAreas.join(', ')} · Up to {row.data.maxGuests} guests</p><p>Private contact: {row.data.contactEmail} · {row.data.phone}</p><p>Stated availability: {row.data.availableFrom} to {row.data.availableTo}. Unavailable: {row.data.unavailableDates.join(', ')||'None listed'}.</p><div className="draft-photos">{row.data.images.map(id=><img key={id} src={'/api/demo/image?id='+id} alt={'Submitted photo for '+row.data.name} width={160} height={120}/>)}</div>{row.data.menus.map(m=><details className="catering-review-menu" key={m.id}><summary>{m.name} · {money(m.perPlate/100)}/plate · minimum {m.minimumGuests}</summary><p>{m.diet.replaceAll('_',' ')} · {m.serviceStyle.replaceAll('_',' ')}</p><p>{m.dishes}</p><p>{m.inclusions}</p><p>Staff: {money(m.staffing/100)} · Equipment: {money(m.equipment/100)} · Transport: {money(m.transport/100)} · Tax: {m.taxBps/100}%</p><p>Optional: {m.optionalName||'None'} · {money(m.optionalPerGuest/100)}/billable guest. Additional guest: {money(m.extraGuestRate/100)}.</p><p>Guest-count deadline: {m.guestChangeDeadlineDays} days before event.</p><p>{m.cancellationTerms}</p></details>)}{row.review_note&&<div className="notice">Review: {row.review_note}</div>}{adminView&&row.status==='pending_review'&&<div className="stack-form"><label>Review note<textarea minLength={5} maxLength={1000} value={notes[row.id]||''} onChange={e=>setNotes({...notes,[row.id]:e.target.value})}/></label><div className="workspace-actions"><button className="primary" disabled={busy} onClick={()=>review(row,'approved_for_demo')}>Approve for private catalog</button><button className="filter-button" disabled={busy} onClick={()=>review(row,'changes_requested')}>Request changes</button></div></div>}</article>)}</div>}</>;
}
