'use client';
import {useEffect,useState} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {cateringApi} from '@/lib/catering-client';
import {policyLabels,type CateringPolicy} from '@/lib/catering';
import type {CateringCatalog} from '@/lib/catering-server';
export default function CateringPolicyEditor({value,onChange}:{value:CateringPolicy;onChange:(v:CateringPolicy)=>void}){
 const [suppliers,setSuppliers]=useState<CateringCatalog['suppliers']>([]),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();cateringApi<CateringCatalog>('catalog',undefined,controller.signal).then(d=>setSuppliers(d.suppliers)).catch(e=>{if(e.name!=='AbortError')setError('Supplier choices could not load. Refresh before linking caterers.');});return()=>controller.abort();},[]);
 return <section className="catering-menu-editor stack-form"><h3>Catering rules customers see before checkout</h3><label>Who may provide food?<select value={value.mode} onChange={e=>onChange({...value,mode:e.target.value as CateringPolicy['mode'],supplierIds:[]})}>{Object.entries(policyLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label>{['in_house','approved_only'].includes(value.mode)&&<><p>Select the suppliers this venue permits. An empty selection shows no compatible caterers.</p>{error&&<p role="alert" className="error">{error}</p>}{suppliers.map(s=><label className="addon-option" key={s.id}><Checkbox checked={value.supplierIds.includes(s.id)} onCheckedChange={checked=>onChange({...value,supplierIds:checked===true?[...value.supplierIds,s.id]:value.supplierIds.filter(id=>id!==s.id)})}/><span>{s.name}{s.source==='sample'?' (fictional demo)':''}</span></label>)}{value.supplierIds.filter(id=>!suppliers.some(s=>s.id===id)).map(id=><p key={id} className="muted">A previously linked supplier is no longer available for discovery. Unlink it by changing the policy and reselecting approved suppliers.</p>)}</>}<div className="form-grid"><label>Mandatory catering / kitchen fee (₹)<input type="number" min={0} max={1000000} step="0.01" value={value.venueFee/100} onChange={e=>onChange({...value,venueFee:Math.round(Number(e.target.value)*100)})}/></label><label>Minimum food spend, before tax (₹)<input type="number" min={0} max={1000000} step="0.01" value={value.minimumFoodSpend/100} onChange={e=>onChange({...value,minimumFoodSpend:Math.round(Number(e.target.value)*100)})}/></label></div><label>Kitchen access, restrictions and catering notes<textarea maxLength={700} value={value.notes} onChange={e=>onChange({...value,notes:e.target.value})}/></label><p className="muted">These charges belong to the separate catering estimate. Do not duplicate a fee already included in venue rental. The policy is published only after admin review.</p></section>;
}
