"use client";
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {MapPin,Users,ArrowUpRight,Search,ShieldCheck,CalendarCheck,Building2,Trees,PartyPopper,Hotel,Flower2} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {type Venue,venueTypes,money,indiaToday} from '@/lib/venues';
import {makeQuote,lastBookableDate,type Pricing} from '@/lib/booking';
import {demoApi} from '@/lib/demo-client';
export function Pick({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="pick"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>}
export default function Explore({initialCatalog}:{initialCatalog:{venues:Venue[];pricing:Record<string,Pricing>}}){
 const [catalog,setCatalog]=useState(initialCatalog);const venues=catalog.venues;const initialPricing=catalog.pricing;const localities=['All Bengaluru',...Array.from(new Set(venues.map(v=>v.area))).sort()];
 useEffect(()=>{const update=()=>demoApi('catalog').then(setCatalog).catch(()=>{});const timer=setInterval(update,10000);window.addEventListener('focus',update);return ()=>{clearInterval(timer);window.removeEventListener('focus',update);};},[]);
 const [area,setArea]=useState('All Bengaluru');const [date,setDate]=useState('');const [guests,setGuests]=useState(0);const [budget,setBudget]=useState(1000000);const [type,setType]=useState('All venues');const [query,setQuery]=useState('');const [sort,setSort]=useState('featured');const [blocked,setBlocked]=useState<string[]>([]);const [checkedDate,setCheckedDate]=useState('');const [error,setError]=useState('');
 useEffect(()=>{if(!date){setCheckedDate('');setError('');return;}const controller=new AbortController();const update=()=>demoApi('calendar?date='+date,undefined,controller.signal).then(d=>{setBlocked(d.unavailable);setCheckedDate(date);setError('');}).catch(e=>{if(!controller.signal.aborted){setError(e.message);setCheckedDate('');}});update();const timer=setInterval(update,5000);return ()=>{controller.abort();clearInterval(timer);};},[date]);
 const totals=Object.fromEntries(venues.map(v=>[v.slug,makeQuote(v,initialPricing[v.slug],{venueSlug:v.slug,date:date||indiaToday(),guests:1,packageId:'marriage-24h',extraHours:0,addons:[]}).total/100]));
 const results=venues.filter(v=>(area==='All Bengaluru'||v.area===area)&&(type==='All venues'||v.type===type)&&v.capacity>=guests&&totals[v.slug]<=budget&&(!query||(v.name+' '+v.area).toLowerCase().includes(query.toLowerCase()))&&(!date||(checkedDate===date&&!blocked.includes(v.slug)))).sort((a,b)=>sort==='price-low'?totals[a.slug]-totals[b.slug]:sort==='capacity'?b.capacity-a.capacity:0);
 const clear=()=>{setArea('All Bengaluru');setDate('');setGuests(0);setBudget(1000000);setType('All venues');setQuery('');};
 return <main><section className="discovery"><div className="intro"><div><p className="eyebrow">BENGALURU / OWNER DEMONSTRATION</p><h1>Find your venue.<br/><em>Lock your date and price.</em></h1><p className="intro-copy">Explore sample spaces and approved owner listings. Try booking from calendar to confirmation.</p></div><div className="promise-note"><ShieldCheck size={32}/><strong>One clear price.</strong><span>No enquiry. No callback.<br/>A self-serve booking demonstration.</span></div></div><form className="search-panel" onSubmit={e=>{e.preventDefault();document.getElementById('results')?.scrollIntoView({behavior:'smooth'});}}><div className="search-field"><label>Locality</label><Pick label="Locality" value={area} options={localities} onChange={setArea}/></div><div className="search-field"><label htmlFor="event-date">Venue access start date</label><input id="event-date" type="date" min={indiaToday()} max={lastBookableDate()} value={date} onChange={e=>setDate(e.target.value)}/></div><div className="search-field"><label htmlFor="guests">Guests</label><input id="guests" type="number" min="1" max="2000" placeholder="Guest count" value={guests||''} onChange={e=>setGuests(Number(e.target.value))}/></div><div className="search-field"><label htmlFor="budget">Total budget</label><select id="budget" value={budget} onChange={e=>setBudget(Number(e.target.value))}><option value="1000000">Any budget</option><option value="50000">Up to ₹50,000</option><option value="100000">Up to ₹1 lakh</option><option value="150000">Up to ₹1.5 lakh</option><option value="200000">Up to ₹2 lakh</option></select></div><button className="primary search-button"><Search size={18}/>Find venues</button></form><div className="search-notes"><span><CalendarCheck size={16}/>24-hour marriage package availability</span><span><ShieldCheck size={16}/>Itemized totals, including sample tax</span><span>No real reservation or payment</span></div></section>
 <section className="catalog" id="results"><div className="catalog-toolbar"><div className="category-tabs">{venueTypes.map((t,i)=>{const Icon=[Building2,Trees,Trees,Hotel,PartyPopper,Flower2][i];return <button className={type===t?'category active':'category'} aria-pressed={type===t} key={t} onClick={()=>setType(t)}><Icon size={18}/>{t}</button>;})}</div></div><div className="results-heading"><div><p className="eyebrow">YOUR CELEBRATION STARTS HERE</p><h2>Spaces across Bengaluru</h2><p aria-live="polite">{date&&checkedDate!==date?'Checking shared availability...':`${results.length} demo venues${date?' available on '+date:''}`} · Sample spaces and owner-submitted listings</p></div><div className="catalog-search"><input aria-label="Search venue name or locality" placeholder="Search name or locality" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Sort venues" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="price-low">Total: low to high</option><option value="capacity">Largest capacity</option></select></div></div>{error&&<div className="error" role="alert">{error}</div>}
 <div className="venue-grid">{results.map((v,i)=><a href={`/venues/${v.slug}?${new URLSearchParams({...date?{date}:{},...guests?{guests:String(guests)}:{}})}`} className="venue-card" key={v.slug}><div className="card-image"><img src={v.image} alt={v.source==='owner'?v.name+' — owner-supplied photo':`Illustrative ${v.type.toLowerCase()} setting, not a real listed venue`} loading={i<3?'eager':'lazy'} width="800" height="540"/><span className="image-label">{v.type}</span><span className="sample-label">{v.source==='owner'?'OWNER LISTING · DEMO':'SAMPLE VENUE'}</span></div><div className="card-content"><p className="location"><MapPin size={14}/>{v.area}, Bengaluru</p><h3>{v.name}<ArrowUpRight size={19}/></h3><p className="capacity"><Users size={16}/>Up to {v.capacity} guests · {v.type==='Outdoor venue'?'Outdoor':v.type==='Resort'?'Resort venue':'Indoor'}</p><div className="card-bottom"><div><strong>{money(totals[v.slug])}</strong><span> / 24 hours</span><small>Mandatory charges + sample tax included</small></div><ShieldCheck size={20}/></div><div className="card-action">{date?'Choose this date':'View dates & full price'}<ArrowUpRight size={16}/></div></div></a>)}</div>{!results.length&&(!date||checkedDate===date)&&<Empty className="empty-state"><EmptyHeader><EmptyTitle>No matching demo venues</EmptyTitle><EmptyDescription>Try a different date, budget or locality.</EmptyDescription></EmptyHeader><button className="primary" onClick={clear}>Clear filters</button></Empty>}
 <section className="planning-band"><div><p className="eyebrow">PLAN WITH CLARITY</p><h2>Know what to ask before you book.</h2><p>Venue comparisons, transparent rental costs and practical planning for Bengaluru celebrations.</p></div><Link href="/guides" className="filter-button">Read planning guides <ArrowUpRight size={18}/></Link></section></section></main>;
}
