'use client';
import {useState} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {indiaToday} from '@/lib/venues';
import {shiftDate} from '@/lib/booking';
import {publicationSchema,type Publication} from '@/lib/publication';
import {demoApi} from '@/lib/demo-client';
export function CalendarFields({value,onChange}:{value:Publication['calendar'];onChange:(c:Publication['calendar'])=>void}){
 const [blocked,setBlocked]=useState(value?.unavailable.join(', ')||'');
 return <div className="stack-form"><label className="addon-option"><Checkbox checked={!!value} onCheckedChange={checked=>{setBlocked('');onChange(checked===true?{from:indiaToday(),to:shiftDate(indiaToday(),30),unavailable:[]}:null);}}/><span>I can supply current date availability. All days in the range are reported available except the unavailable dates below.</span></label>{value&&<><div className="form-grid"><label>Availability from<input type="date" required value={value.from} onChange={e=>onChange({...value,from:e.target.value})}/></label><label>Availability until<input type="date" required value={value.to} onChange={e=>onChange({...value,to:e.target.value})}/></label></div><label>Unavailable dates (YYYY-MM-DD, separated by commas)<textarea value={blocked} onChange={e=>{setBlocked(e.target.value);onChange({...value,unavailable:Array.from(new Set(e.target.value.split(/[,\s]+/).filter(Boolean)))});}} placeholder="2026-12-10, 2026-12-11"/></label></>}<p className="muted">Leave unchecked if dates are not confirmed. This read-only calendar does not reserve dates or synchronize with other booking channels. Refresh at least weekly; older information appears as unconfirmed.</p></div>;
}
export function PublicationFields({value,onChange,admin=false}:{value:Publication;onChange:(p:Publication)=>void;admin?:boolean}){return <section className="catering-menu-editor stack-form"><h3>Public listing permission & calendar</h3>{admin&&<label>Publication route<select value={value.source} onChange={event=>onChange({...value,source:event.target.value as Publication['source'],consent:false,authorizationNote:'',calendar:null,calendarUpdatedAt:null})}><option value="owner">Venue owner approved public display</option><option value="admin">Admin direct: RiteVenue has independent rights</option></select></label>}{value.source==='admin'&&admin&&<label>How did RiteVenue verify the listing and obtain rights to its photos?<textarea minLength={20} maxLength={1000} value={value.authorizationNote} onChange={event=>onChange({...value,authorizationNote:event.target.value})} placeholder="Describe the source of the listing details and the licence or ownership of each photo. Do not paste private contact details."/><span className="muted">Write the public description independently; do not copy private application text. Upload only RiteVenue-owned or independently licensed photos. Application photos are for private review. Public prices and availability remain unconfirmed until the venue verifies them.</span></label>}<label className="addon-option"><Checkbox checked={value.consent} onCheckedChange={checked=>onChange({...value,consent:checked===true})}/><span>{value.source==='admin'?'I confirm RiteVenue has the rights to publish these accurate venue details and independently supplied photos on its public website.':'I have the venue owner’s permission to publish its name, address, photographs, prices, description and reported calendar on the public RiteVenue website.'}</span></label>{value.source==='owner'?<CalendarFields value={value.calendar} onChange={calendar=>onChange({...value,calendar})}/>:<p className="muted">Dates cannot be marked available for admin-direct listings without venue confirmation. The public calendar will show unconfirmed dates.</p>}<p className="muted">Admin reviews each listing before publication. Saving listing edits removes the public listing until it is approved again.</p></section>;}
export function PublishedCalendarEditor({id,initial,updatedAt,onSaved}:{id:string;initial:Publication['calendar'];updatedAt:string;onSaved:()=>Promise<void>}){
 const [calendar,setCalendar]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function save(){setError('');setNotice('');const parsed=publicationSchema.shape.calendar.safeParse(calendar);if(!parsed.success){setError(parsed.error.issues[0].message);return;}setBusy(true);try{await demoApi('public-calendar',{id,calendar:parsed.data,expectedUpdatedAt:updatedAt});setNotice('Public calendar updated. Your listing stays visible.');await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="catering-review-menu"><summary>Update public calendar</summary><fieldset disabled={busy} className="catering-fieldset stack-form"><CalendarFields value={calendar} onChange={setCalendar}/><button type="button" className="primary" onClick={save}>{busy?'Saving…':'Publish calendar update'}</button>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}</fieldset></details>;
}
