"use client";
import {useState,useEffect} from 'react';
import Link from 'next/link';
import {MapPin,ImageOff,ArrowUpRight,Upload,Search} from 'lucide-react';
import type {GoogleVenue} from '@/lib/google-catalog';
export default function RealVenues(){
 const [count,setCount]=useState(0);const [configured,setConfigured]=useState(false);const [ready,setReady]=useState(false);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [venues,setVenues]=useState<GoogleVenue[]>([]);const [page,setPage]=useState(0);
 async function status(){const response=await fetch('/api/venue-catalog',{cache:'no-store'});const data=await response.json() as {error?:string;count:number;googleConfigured:boolean};if(!response.ok)throw new Error(data.error||'Could not load catalog');setCount(data.count);setConfigured(data.googleConfigured);setReady(true);}
 useEffect(()=>{status().catch(e=>setError(e.message));},[]);
 async function importCatalog(){if(!file)return;setBusy(true);setError('');setNotice('');try{if(file.size>524288)throw new Error('Choose a JSON file smaller than 512 KB');const raw=await file.text();const r=await fetch('/api/venue-catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:raw});const data=await r.json() as {error?:string;added:number;total:number};if(!r.ok)throw new Error(data.error||'Import failed');setCount(data.total);setNotice(`${data.added} new IDs imported. ${data.total} IDs in your catalog.`);setVenues([]);setPage(0);await status();}catch(e){setError(e instanceof Error?e.message:'Could not import catalog');}finally{setBusy(false);}}
 async function loadPage(next:number){setBusy(true);setError('');setNotice('');setVenues([]);try{const r=await fetch('/api/venue-catalog/resolve?page='+next,{method:'POST',cache:'no-store'});const data=await r.json() as {error?:string;venues:GoogleVenue[];page:number;total:number};if(!r.ok)throw new Error(data.error||'Could not load real venues');setVenues(data.venues);setPage(data.page);setCount(data.total);}catch(e){setError(e instanceof Error?e.message:'Could not load real venues');}finally{setBusy(false);}}
 return <main className="content-page"><div className="breadcrumb"><Link href="/">Sample booking experience</Link><span>/</span>Real venue discovery</div><p className="eyebrow">BENGALURU · PRIVATE DISCOVERY PILOT</p><h1>Meet the real venues.</h1><p className="prose">Import your ID catalog, then load current venue information. Discovered venues are not yet RiteVenue booking partners.</p><section className="catalog-connect"><div><h2>Connect your venue catalog</h2><p>Choose <code>compliant_venues_catalog.json</code> from the Python script. Names, addresses and photos are not imported into the database.</p><label htmlFor="catalog-file">ID-only JSON catalog</label><input id="catalog-file" type="file" accept=".json,application/json" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="primary" onClick={importCatalog} disabled={!file||busy}><Upload size={17}/>{busy?'Working…':'Import venue IDs'}</button></div><div className="connection-status"><h2>{ready?`${count} venue IDs saved`:'Checking your catalog…'}</h2><p>{configured?'Google connection configured. Load six venues at a time.':'Google connection is not configured yet. Add the server-side API key before loading real details.'}</p><button className="primary" disabled={busy||!configured||!count} onClick={()=>loadPage(1)}><Search size={17}/>Load real venue details</button><p className="muted">Live lookups can incur Google API charges. This private pilot limits lookups to 120 provider requests per day per user.</p></div></section>
 {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}{busy&&<p role="status" className="notice">Working on your catalog…</p>}
 <div className="notice">Booking is not enabled for discovered venues. Availability, capacity and prices need owner confirmation. Locality tags describe your search and do not verify the venue’s address.</div>
 {venues.length>0&&<><div className="results-heading"><h2>Real venue results</h2><span className="google-brand" translate="no">Google Maps</span></div><div className="venue-grid">{venues.map(venue=><article className="venue-card live-venue" key={venue.venue_uuid}><div className="card-image">{venue.photo?<LivePhoto photo={venue.photo} name={venue.name}/>:<div className="no-photo"><ImageOff size={28}/><span>No photo available</span></div>}<span className="image-label">Booking not enabled</span></div><div className="card-content"><h3>{venue.name||'Venue details unavailable'}</h3>{venue.error?<p className="muted">{venue.error}</p>:<><p className="location"><MapPin size={15}/>{venue.address||'Address not provided'}</p>{venue.businessStatus&&venue.businessStatus!=='OPERATIONAL'&&<p className="muted">Google status: {venue.businessStatus.replaceAll('_',' ').toLowerCase()}</p>}</>}
 {venue.photo&&<div className="photo-credits">{venue.photo.authors.map((author,i)=><div key={i}>{author.photoUri&&<img src={author.photoUri} alt="" referrerPolicy="no-referrer" width="24" height="24"/>}{author.uri?<a href={author.uri} target="_blank" rel="noopener noreferrer">{author.name}</a>:<span>{author.name}</span>}</div>)}<a href={venue.photo.sourceUrl} target="_blank" rel="noopener noreferrer">View original photo on Google Maps</a></div>}
 {venue.providerAttributions.map((a,i)=><p className="muted" key={i}>{a.uri?<a href={a.uri} target="_blank" rel="noopener noreferrer">{a.name}</a>:a.name}</p>)}<div className="card-bottom"><span>Price & capacity unconfirmed</span>{venue.mapsUrl&&<a className="maps-link" href={venue.mapsUrl} target="_blank" rel="noopener noreferrer">Google Maps <ArrowUpRight size={15}/></a>}</div></div></article>)}</div><nav className="catalog-pagination" aria-label="Real venue pages"><button className="filter-button" disabled={busy||page<=1} onClick={()=>loadPage(page-1)}>Previous</button><span>Page {page} of {Math.ceil(count/6)}</span><button className="filter-button" disabled={busy||page*6>=count} onClick={()=>loadPage(page+1)}>Next</button></nav></>}
 <p className="muted">Google Maps content is subject to <a href="https://maps.google.com/help/terms_maps/" target="_blank" rel="noopener noreferrer" className="underline">Google Maps terms</a> and <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="underline">Google’s privacy policy</a>.</p></main>
}
function LivePhoto({photo,name}:{photo:NonNullable<GoogleVenue['photo']>;name:string|null}){const [failed,setFailed]=useState(false);return failed?<div className="no-photo"><ImageOff size={28}/><span>Photo could not be loaded</span></div>:<img src={photo.uri} alt={name?`Google Maps photo of ${name}`:'Venue photo from Google Maps'} referrerPolicy="no-referrer" onError={()=>setFailed(true)} width="800" height="540"/>;}
