'use client';
import type {RentalDetails} from '@/lib/venue-offers';

type Tax=RentalDetails['offers'][number]['tax'];
const unconfirmedTax=():Tax=>({status:'unconfirmed',rate:null});
function Amount({label,value,onChange}:{label:string;value:number|null;onChange:(n:number|null)=>void}){return <label>{label} (₹)<input type="number" min={0} step="0.01" max={1000000} value={value===null?'':value/100} placeholder="Unconfirmed" onChange={e=>onChange(e.target.value===''?null:Math.round(Number(e.target.value)*100))}/></label>;}
function TaxFields({value,onChange}:{value:Tax;onChange:(t:Tax)=>void}){return <div className="form-grid"><label>GST treatment<select value={value.status} onChange={e=>onChange({status:e.target.value as Tax['status'],rate:null})}><option value="unconfirmed">Unconfirmed</option><option value="included">Included in amount</option><option value="extra">Extra</option></select></label>{value.status==='extra'&&<label>GST rate (%)<input type="number" min={0} max={100} step="0.01" required value={value.rate??''} onChange={e=>onChange({...value,rate:e.target.value===''?null:Number(e.target.value)})}/></label>}</div>;}
function References({label,choices,value,onChange}:{label:string;choices:{id:string;name:string}[];value:string[];onChange:(v:string[])=>void}){return <fieldset><legend>{label}</legend>{choices.length?choices.map(c=><label key={c.id} className="addon-option"><input type="checkbox" checked={value.includes(c.id)} onChange={e=>onChange(e.target.checked?[...value,c.id]:value.filter(id=>id!==c.id))}/>{c.name||'Unnamed'}</label>):<p className="muted">None added.</p>}</fieldset>;}
export default function RentalOfferEditor({value,onChange}:{value:RentalDetails;onChange:(d:RentalDetails)=>void}){
 function change<K extends keyof RentalDetails>(key:K,next:RentalDetails[K]){onChange({...value,[key]:next});}
 return <section className="stack-form"><h3>Flexible rental offers</h3><p>Enter only confirmed information. Blank prices, times and quantities mean unconfirmed—not free or included. Amounts are stored exactly as entered; GST is not silently added. No booking or payment is enabled.</p>
 <h4>Spaces within the property</h4><p className="muted">Optional for a single hall. Add Lawn, Hall or Grove before creating combinations.</p>
 {value.spaces.map((s,i)=><fieldset key={s.id} className="stack-form"><div className="form-grid"><label>Space name<input required maxLength={120} value={s.name} onChange={e=>change('spaces',value.spaces.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/></label><label>Capacity (optional)<input type="number" min={1} max={50000} value={s.capacity??''} onChange={e=>change('spaces',value.spaces.map((x,j)=>j===i?{...x,capacity:e.target.value===''?null:Number(e.target.value)}:x))}/></label></div><button type="button" onClick={()=>onChange({...value,spaces:value.spaces.filter((_,j)=>j!==i),offers:value.offers.map(o=>({...o,spaceIds:o.spaceIds.filter(id=>id!==s.id)}))})}>Remove space</button></fieldset>)}
 <button type="button" disabled={value.spaces.length>=10} onClick={()=>change('spaces',[...value.spaces,{id:crypto.randomUUID(),name:'',capacity:null}])}>+ Add space</button>
 <h4>Rental packages and combinations</h4>
 {value.offers.map((o,i)=>{const update=(next:Partial<typeof o>)=>change('offers',value.offers.map((x,j)=>j===i?{...x,...next}:x));return <fieldset key={o.id} className="stack-form"><label>Offer name<input required maxLength={120} value={o.name} onChange={e=>update({name:e.target.value})} placeholder="24-hour marriage / Lawn + Hall"/></label><References label="Spaces included (empty means the whole venue)" choices={value.spaces} value={o.spaceIds} onChange={spaceIds=>update({spaceIds})}/><div className="form-grid"><label>Package status<select value={o.status} onChange={e=>update({status:e.target.value as typeof o.status})}><option value="available">Offered</option><option value="not_applicable">Not applicable</option><option value="not_available">Not available</option></select></label><Amount label="Venue rental per event" value={o.amount} onChange={amount=>update({amount})}/></div><TaxFields value={o.tax} onChange={tax=>update({tax})}/><div className="form-grid"><label>Start time<input type="time" value={o.start??''} onChange={e=>update({start:e.target.value||null})}/></label><label>End time<input type="time" value={o.end??''} onChange={e=>update({end:e.target.value||null})}/></label><label>Ends on<select value={o.endDay} onChange={e=>update({endDay:Number(e.target.value)})}><option value={0}>Same day</option><option value={1}>Next day</option><option value={2}>Two days later</option></select></label><label>Food arrangement<select value={o.food} onChange={e=>update({food:e.target.value as typeof o.food})}><option value="unconfirmed">Unconfirmed</option><option value="optional">Optional, charged separately</option><option value="required">Menu purchase required, charged separately</option><option value="not_included">Not included in rental</option></select></label></div><label>Offer terms<textarea maxLength={500} value={o.notes} onChange={e=>update({notes:e.target.value})}/></label><button type="button" disabled={value.offers.length===1} onClick={()=>onChange({...value,offers:value.offers.filter((_,j)=>j!==i),charges:value.charges.map(c=>({...c,offerIds:c.offerIds.filter(id=>id!==o.id)})),menus:value.menus.map(m=>({...m,offerIds:m.offerIds.filter(id=>id!==o.id)}))})}>Remove offer</button></fieldset>;})}
 <button type="button" disabled={value.offers.length>=15} onClick={()=>change('offers',[...value.offers,{id:crypto.randomUUID(),name:'',spaceIds:[],status:'available',amount:null,tax:unconfirmedTax(),start:null,end:null,endDay:0,food:'unconfirmed',notes:''}])}>+ Add rental offer</button>
 <h4>Facilities and inclusions</h4>
 {value.facilities.map((f,i)=>{const update=(next:Partial<typeof f>)=>change('facilities',value.facilities.map((x,j)=>j===i?{...x,...next}:x));return <fieldset key={i}><div className="form-grid"><label>Facility<input required maxLength={120} value={f.name} onChange={e=>update({name:e.target.value})} placeholder="AC rooms with attached restroom"/></label><label>Quantity (optional)<input type="number" min={1} max={50000} value={f.quantity??''} onChange={e=>update({quantity:e.target.value===''?null:Number(e.target.value)})}/></label><label>Status<select value={f.status} onChange={e=>update({status:e.target.value as typeof f.status})}><option value="unconfirmed">Unconfirmed</option><option value="included">Included</option><option value="not_available">Not available</option></select></label></div><button type="button" onClick={()=>change('facilities',value.facilities.filter((_,j)=>j!==i))}>Remove facility</button></fieldset>;})}
 <button type="button" disabled={value.facilities.length>=25} onClick={()=>change('facilities',[...value.facilities,{name:'',quantity:null,status:'unconfirmed'}])}>+ Add facility</button>
 <h4>Separate charges</h4>
 {value.charges.map((c,i)=>{const update=(next:Partial<typeof c>)=>change('charges',value.charges.map((x,j)=>j===i?{...x,...next}:x));return <fieldset key={i} className="stack-form"><label>Charge name<input required maxLength={120} value={c.name} onChange={e=>update({name:e.target.value})} placeholder="Cleaning / extra hour / chair rental"/></label><Amount label="Charge" value={c.amount} onChange={amount=>update({amount})}/><TaxFields value={c.tax} onChange={tax=>update({tax})}/><label>Charged per<select value={c.basis} onChange={e=>update({basis:e.target.value as typeof c.basis})}><option value="per_event">Event</option><option value="per_hour">Hour</option><option value="per_item">Item</option></select></label><label><input type="checkbox" checked={c.required} onChange={e=>update({required:e.target.checked})}/> Mandatory charge</label><References label="Applies to these offers (empty means all)" choices={value.offers} value={c.offerIds} onChange={offerIds=>update({offerIds})}/><button type="button" onClick={()=>change('charges',value.charges.filter((_,j)=>j!==i))}>Remove charge</button></fieldset>;})}
 <button type="button" disabled={value.charges.length>=15} onClick={()=>change('charges',[...value.charges,{name:'',amount:null,basis:'per_event',tax:unconfirmedTax(),required:false,offerIds:[]}])}>+ Add charge</button>
 <h4>Venue food menus (separate from rental)</h4>
 {value.menus.map((m,i)=>{const update=(next:Partial<typeof m>)=>change('menus',value.menus.map((x,j)=>j===i?{...x,...next}:x));return <fieldset key={i} className="stack-form"><label>Menu name<input required maxLength={120} value={m.name} onChange={e=>update({name:e.target.value})}/></label><div className="form-grid"><label>Diet<select value={m.diet} onChange={e=>update({diet:e.target.value as typeof m.diet})}><option value="unconfirmed">Unconfirmed</option><option value="vegetarian">Vegetarian</option><option value="non_vegetarian">Non-vegetarian</option></select></label><label>Serving style<select value={m.style} onChange={e=>update({style:e.target.value as typeof m.style})}><option value="unconfirmed">Unconfirmed</option><option value="buffet">Buffet</option><option value="plantain_leaf">Plantain leaf</option><option value="served">Served</option></select></label></div><Amount label="Per person" value={m.perPerson} onChange={perPerson=>update({perPerson})}/><TaxFields value={m.tax} onChange={tax=>update({tax})}/><label>Minimum billable guests (optional)<input type="number" min={1} max={50000} value={m.minimumGuests??''} onChange={e=>update({minimumGuests:e.target.value===''?null:Number(e.target.value)})}/></label><References label="Applies to these offers (empty means all)" choices={value.offers} value={m.offerIds} onChange={offerIds=>update({offerIds})}/><button type="button" onClick={()=>change('menus',value.menus.filter((_,j)=>j!==i))}>Remove menu</button></fieldset>;})}
 <button type="button" disabled={value.menus.length>=10} onClick={()=>change('menus',[...value.menus,{name:'',diet:'unconfirmed',style:'unconfirmed',perPerson:null,tax:unconfirmedTax(),minimumGuests:null,offerIds:[]}])}>+ Add menu</button>
 </section>;
}
