"use client";
import {useState,useEffect} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {Pick} from '@/components/explore';
import {indiaToday,type Venue} from '@/lib/venues';
import Link from 'next/link';
export default function RequestForm({venue}:{venue:Venue}){
const [date,setDate]=useState('');const [guests,setGuests]=useState('');const [occasion,setOccasion]=useState(venue.occasions[0]);const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [receipt,setReceipt]=useState('');const [key,setKey]=useState('');
useEffect(()=>{const q=new URLSearchParams(window.location.search);setDate(q.get('date')||'');setGuests(q.get('guests')||'');setKey(crypto.randomUUID());},[]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(!consent){setError('Please acknowledge the preview terms.');return;}setBusy(true);const data=new FormData(e.currentTarget);try{const res=await fetch('/api/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({venueSlug:venue.slug,date,guests:Number(guests),occasion,name:data.get('name'),email:data.get('email'),notes:data.get('notes'),website:data.get('website'),consent,requestKey:key})});const result=await res.json() as {error?:string;id:string};if(!res.ok)throw new Error(result.error||'Could not save your request.');setReceipt(result.id);}catch(e){setError(e instanceof Error?e.message:'Could not save. Please try again.');}finally{setBusy(false);}}
if(receipt)return <div className="success-box" role="status"><h2>Your test request is saved.</h2><p>No venue has been contacted and no date is reserved.</p><Link href={'/requests/'+receipt} className="primary">View request receipt</Link><p className="muted">Keep the receipt link to revisit your request.</p></div>;
return <form className="stack-form" onSubmit={submit}><label>Event date<input type="date" required min={indiaToday()} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Number of guests<input type="number" required min="1" max={venue.capacity} value={guests} onChange={e=>setGuests(e.target.value)} placeholder={`Up to ${venue.capacity}`}/></label><label>Occasion<Pick label="Occasion" value={occasion} onChange={setOccasion} options={venue.occasions}/></label><label>Your name<input name="name" autoComplete="name" required minLength={2} maxLength={80} placeholder="Use a test name"/></label><label>Email<input name="email" type="email" autoComplete="email" required maxLength={160} placeholder="you@example.com"/></label><label>Anything else? <span className="muted">Optional</span><textarea name="notes" maxLength={1000} placeholder="Event timing or accessibility needs"/></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="check-label"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>I understand this saves a test request and agree to the <Link href="/privacy" className="underline">preview privacy terms</Link>.</span></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||!key} type="submit">{busy?'Saving request…':'Try a booking request'}</button><p className="muted">No payment. No confirmed booking. Please use test contact details in this private preview.</p></form>}
