import {z} from 'zod';
import {validDate,shiftDate} from './booking';
import {indiaToday} from './venues';
const money=z.number().int().min(0).max(100000000);
const day=z.string().refine(validDate,'Use a valid date');
export const policySchema=z.object({mode:z.enum(['unconfirmed','in_house','approved_only','external_allowed']).default('unconfirmed'),supplierIds:z.array(z.string().min(1).max(80)).max(30).default([]),notes:z.string().trim().max(700).default(''),venueFee:money.default(0),minimumFoodSpend:money.default(0)}).strict();
export type CateringPolicy=z.infer<typeof policySchema>;
export const policyLabels:Record<CateringPolicy['mode'],string>={unconfirmed:'Catering policy not confirmed',in_house:'In-house catering only',approved_only:'Venue-approved caterers only',external_allowed:'External caterers permitted'};
export const menuSchema=z.object({id:z.string().min(1).max(80),name:z.string().trim().min(3).max(80),diet:z.enum(['vegetarian','non_vegetarian']),serviceStyle:z.enum(['buffet','served','banana_leaf']),dishes:z.string().trim().min(10).max(1000),inclusions:z.string().trim().min(10).max(800),perPlate:money.refine(v=>v>=100,'Enter a per-plate price of at least ₹1'),minimumGuests:z.number().int().min(1).max(2000),staffing:money,equipment:money,transport:money,taxBps:z.number().int().min(0).max(10000),extraGuestRate:money,guestChangeDeadlineDays:z.number().int().min(0).max(60),optionalName:z.string().trim().max(80),optionalPerGuest:money,cancellationTerms:z.string().trim().min(10).max(800)}).strict().refine(m=>!m.optionalPerGuest||!!m.optionalName,'Name the optional add-on');
export type CateringMenu=z.infer<typeof menuSchema>;
export const supplierSchema=z.object({id:z.string().uuid(),name:z.string().trim().min(3).max(100),description:z.string().trim().min(30).max(2000),contactEmail:z.string().email().max(200),phone:z.string().trim().min(7).max(30),serviceAreas:z.array(z.string().trim().min(2).max(100)).min(1).max(40),maxGuests:z.number().int().min(1).max(2000),availableFrom:day,availableTo:day,unavailableDates:z.array(day).max(365),menus:z.array(menuSchema).min(1).max(6),images:z.array(z.string().uuid()).max(6),rightsConfirmed:z.literal(true),submit:z.boolean()}).strict().refine(d=>d.availableTo>=d.availableFrom,'Availability end must be after its start').refine(d=>d.menus.every(m=>m.minimumGuests<=d.maxGuests),'Menu minimum guests cannot exceed supplier capacity').refine(d=>new Set(d.menus.map(m=>m.id)).size===d.menus.length,'Menu IDs must be unique');
export type SupplierDraft=z.infer<typeof supplierSchema>;
export type Caterer=Omit<SupplierDraft,'contactEmail'|'phone'|'rightsConfirmed'|'submit'|'images'>&{source:'sample'|'supplier';images:string[]};
export const estimateSelectionSchema=z.object({venueSlug:z.string().min(1).max(100),supplierId:z.string().min(1).max(80),menuId:z.string().min(1).max(80),date:day,guests:z.number().int().min(1).max(2000),optional:z.boolean()}).strict();
export type CateringSelection=z.infer<typeof estimateSelectionSchema>;
export function supplierView(d:SupplierDraft):Caterer{const {contactEmail,phone,rightsConfirmed,submit,...rest}=d;return {...rest,source:'supplier',images:d.images.map(id=>'/api/demo/image?id='+id)};}
export function samplePolicy(slug:string,type:string):CateringPolicy{return policySchema.parse(type==='Hotel'?{mode:'in_house',supplierIds:['sample-atrium-kitchen'],notes:'Fictional hotel policy: use the sample in-house kitchen. Venue rental and food are separate.',minimumFoodSpend:10000000}:type==='Wedding hall'?{mode:'approved_only',supplierIds:['sample-saffron-table'],notes:'Fictional policy: only the listed caterer is permitted. Venue kitchen fee is included in catering estimates.',venueFee:250000}:{mode:'external_allowed',notes:'Fictional policy: outside caterers may use the event space. Confirm facilities and setup access before a real event.',venueFee:150000});}
export function supplierCompatibility(policy:CateringPolicy,supplier:Caterer,area:string,date:string,guests:number){
 if(!Number.isInteger(guests)||guests<1)return 'Enter a valid guest count.';
 if(policy.mode==='unconfirmed')return 'The venue has not confirmed its catering policy.';
 if(policy.mode!=='external_allowed'&&!policy.supplierIds.includes(supplier.id))return 'This caterer is not permitted by the venue.';
 const areas=supplier.serviceAreas.map(a=>a.toLowerCase().trim());if(!areas.includes('all bengaluru')&&!areas.includes(area.toLowerCase().trim()))return 'This locality is outside the supplier’s stated service area.';
 if(!validDate(date)||date<indiaToday()||date>shiftDate(indiaToday(),365))return 'Choose an event date within the next 12 months.';
 if(date<supplier.availableFrom||date>supplier.availableTo||supplier.unavailableDates.includes(date))return 'Supplier has not listed availability for this date.';
 if(guests>supplier.maxGuests)return 'Guest count exceeds the supplier’s stated capacity.';
 return null;
}
export function cateringEstimate(supplier:Caterer,menu:CateringMenu,policy:CateringPolicy,selection:CateringSelection){
 const billedGuests=Math.max(selection.guests,menu.minimumGuests);if(billedGuests>supplier.maxGuests)throw new Error('Guest count exceeds supplier capacity');
 const food=billedGuests*menu.perPlate;
 const items=[{label:`Food: ${billedGuests} billable guests`,amount:food},{label:'Minimum food-spend adjustment',amount:Math.max(0,policy.minimumFoodSpend-food)},{label:'Service staff',amount:menu.staffing},{label:'Equipment & crockery',amount:menu.equipment},{label:'Transport',amount:menu.transport},{label:'Venue catering / kitchen fee',amount:policy.venueFee},{label:selection.optional&&menu.optionalName?`${menu.optionalName}: ${billedGuests} guests`:'Optional add-on (not selected)',amount:selection.optional?billedGuests*menu.optionalPerGuest:0},{label:'Platform fee (prototype)',amount:0}];
 const subtotal=items.reduce((s,i)=>s+i.amount,0),tax=Math.round(subtotal*menu.taxBps/10000);
 return {kind:'catering_estimate' as const,reserved:false,venueSlug:selection.venueSlug,supplierId:supplier.id,supplierName:supplier.name,menuId:menu.id,menuName:menu.name,date:selection.date,guests:selection.guests,billedGuests,items,subtotal,tax,taxBps:menu.taxBps,total:subtotal+tax,guestChangeDeadline:shiftDate(selection.date,-menu.guestChangeDeadlineDays),extraGuestRate:menu.extraGuestRate,cancellationTerms:menu.cancellationTerms,createdAt:new Date().toISOString()};
}
export type CateringEstimate=ReturnType<typeof cateringEstimate>;
export function sampleCaterers():Caterer[]{
 const menu=(id:string,name:string,perPlate:number,diet:'vegetarian'|'non_vegetarian'='vegetarian'):CateringMenu=>({id,name,diet,serviceStyle:'buffet',dishes:diet==='vegetarian'?'Welcome drink, vegetable starters, rice, roti, two curries, dal, curd and dessert.':'Welcome drink, chicken starter, vegetable starter, rice, roti, chicken curry, dal and dessert.',inclusions:'One meal service, buffet setup, water station and serving team. No decor or accommodation.',perPlate,minimumGuests:100,staffing:800000,equipment:400000,transport:250000,taxBps:500,extraGuestRate:perPlate,guestChangeDeadlineDays:7,optionalName:'Evening tea & snack',optionalPerGuest:12000,cancellationTerms:'Illustrative package only. No supplier reservation, payment or cancellation charge applies to this prototype.'});
 const base={description:'Fictional catering provider for the private RiteVenue prototype. Menus, prices, capacity and availability are illustrative.',source:'sample' as const,serviceAreas:['All Bengaluru'],availableFrom:indiaToday(),availableTo:shiftDate(indiaToday(),365),unavailableDates:[] as string[],images:['/images/party.jpg']};
 return [{...base,id:'sample-saffron-table',name:'Saffron Table Catering',maxGuests:1200,menus:[{...menu('classic-veg','Classic vegetarian feast',65000),serviceStyle:'banana_leaf'},menu('celebration-veg','Celebration vegetarian buffet',85000)]},{...base,id:'sample-coastal-hearth',name:'Coastal Hearth Caterers',maxGuests:700,unavailableDates:[shiftDate(indiaToday(),7)],menus:[menu('coastal-veg','Coastal vegetarian menu',75000),menu('coastal-mixed','Coastal mixed menu',95000,'non_vegetarian')]},{...base,id:'sample-atrium-kitchen',name:'Atrium Banquet Kitchen',maxGuests:500,menus:[{...menu('hotel-veg','Hotel vegetarian banquet',120000),transport:0,equipment:0},{...menu('hotel-mixed','Hotel mixed banquet',150000,'non_vegetarian'),transport:0,equipment:0}]}];
}
