export type Guide={slug:string;title:string;description:string;category:string;sections:{heading:string;paragraphs:string[];checklist?:string[]}[]};
export const guides:Guide[]=[
 {slug:'bengaluru-wedding-venue-checklist',title:'A wedding venue checklist for Bengaluru couples',description:'Compare guest capacity, access, rental hours and included facilities before choosing a wedding venue in Bengaluru.',category:'START YOUR SHORTLIST',sections:[
 {heading:'Begin with the event you are actually planning',paragraphs:['Write down the ceremony date, the expected guest count and the events that need space. A ceremony, seated meal and evening reception can have different layout requirements even when they share the same venue. Decide which spaces need to operate at the same time before comparing rental prices.','Treat locality as part of the guest experience. Ask where most guests will travel from, whether older relatives need a short transfer and whether accommodation will be arranged separately. Do not choose a venue only because its headline capacity is large.']},
 {heading:'Check the space, not just the photographs',paragraphs:['Ask for a layout showing the stage, seating, dining area, entrances and service routes. The guest capacity should match your chosen arrangement, not an unspecified maximum. Photographs can help you shortlist, but they do not confirm present-day condition or accessibility.'],checklist:['Step-free access and usable toilets','Parking arrangements and drop-off access','Covered backup space for outdoor events','Preparation rooms and secure storage','Entry time, setup access and final exit time','Power backup and who operates it']},
 {heading:'Ask for one complete written quote',paragraphs:['Compare the same event duration and guest count across your shortlist. Ask the owner to identify rental, mandatory charges, taxes, deposits and any conditions that can change the total. If a charge depends on electricity use or overtime, request a measurable allowance and written rate before committing.','RiteVenue publishes owner-supplied venue information. Confirm the venue identity, authority to rent the space, current availability and contract terms directly with the authorized operator.']}
 ]},
 {slug:'understand-venue-rental-pricing',title:'How to compare a fully itemized venue rental quote',description:'A practical breakdown of base rental, mandatory charges, add-ons, advance and balance when comparing wedding venues.',category:'PRICING CLARITY',sections:[
 {heading:'Separate the rental from the full event cost',paragraphs:['A venue rental quote is not automatically a complete wedding budget. Catering, decoration, accommodation and entertainment may be separate purchases. Start by marking exactly which spaces and hours the rental covers, then list the excluded services so they are not mistaken for included benefits.']},
 {heading:'Make mandatory charges visible',paragraphs:['Ask whether air conditioning, backup power, parking, cleaning and basic room access are included or separately charged. An item labelled optional should genuinely be optional for your selected booking. Confirm how taxes are calculated and whether a refundable security deposit is separate from the rental price.','Do not compare a base-rent number from one venue with an all-inclusive total from another. Build a simple comparison using identical access hours, capacity assumptions and inclusions. Request clarification whenever a line item is described only as miscellaneous.'],checklist:['Base rent and access period','Every mandatory venue charge','Only the optional extras you selected','Applicable taxes and any separate refundable deposit','Total commitment, advance and remaining balance','Written cancellation, rescheduling and overtime terms']},
 {heading:'A price lock needs a defined scope',paragraphs:['A useful locked quote identifies the venue, date, access package, guest count and exact inclusions. Keep a dated copy of that agreement and confirmation. Extra hours or a requested scope change should never be confused with an undisclosed mandatory fee.','Rental information on RiteVenue is for planning, not a binding price guarantee. Obtain a written final quote from the venue, including applicable taxes and agreed commercial terms.']}
 ]},
 {slug:'indoor-outdoor-wedding-venue',title:'Indoor or outdoor wedding venue: what to compare',description:'Compare weather backup, guest comfort, access and layout when choosing an indoor hall or outdoor venue in Bengaluru.',category:'CHOOSE YOUR SETTING',sections:[
 {heading:'Think about the whole event',paragraphs:['An outdoor setting may suit a ceremony with open views, while an indoor hall may make it easier to plan lighting, sound and seating within a defined space. Neither format is automatically better. Compare both against your event schedule, guest needs and the work required to make the space usable.']},
 {heading:'Make the backup plan specific',paragraphs:['For an outdoor celebration, ask where every guest will go if the outdoor area cannot be used. A covered corner is not necessarily a workable replacement for the complete ceremony and meal. Confirm whether the backup area is reserved for your event, what it can accommodate and whether moving the event creates additional charges.','For an indoor venue, inspect ventilation, access to different floors and the paths between ceremony and dining spaces. Ask how the layout changes when your full guest count is present.'],checklist:['A backup layout for your actual guest count','Stable walking surfaces and accessible routes','Lighting after sunset and reliable power','Written operating hours and sound conditions','Shelter for guests, equipment and food service','Clear ownership of setup and cleanup responsibilities']},
 {heading:'Use photographs to shortlist, then verify',paragraphs:['Ask for recent, representative images rather than only styled event photographs. Request views of entrances, toilets, parking and service areas as well as the main celebration space. An in-person visit or live video walkthrough can help identify details that a gallery does not show.','Public RiteVenue listings use photographs supplied for display by the venue. Check when photographs were taken and whether they represent the layout available for your event.']}
 ]},
 {slug:'guest-count-and-venue-capacity',title:'Match your guest list to the right venue capacity',description:'Plan seating, dining and circulation before relying on a wedding hall capacity number.',category:'GUEST EXPERIENCE',sections:[
 {heading:'Use a realistic working guest count',paragraphs:['Start with your expected attendance and keep track of what is confirmed, likely and uncertain. Explain that range to the venue operator. A lower rental price is not a saving if your final arrangement cannot comfortably accommodate the event.','Capacity depends on the layout. Standing reception space, theatre-style chairs and round-table dining use a room differently. Ask the operator to confirm the capacity for the specific layout you plan to use.']},
 {heading:'Leave room for more than chairs',paragraphs:['Your event may need a stage, ceremony area, dining circulation, accessible routes and space for staff. Ask for these to appear on the plan, rather than assuming they fit after the guest seating is counted. Confirm permitted capacity and operational requirements with the venue; do not treat a website estimate as a safety assessment.'],checklist:['Guest seating for the actual layout','Space for the ceremony or stage','Dining and service circulation','Clear entrances, exits and accessible routes','Children, older guests and mobility needs','Agreed procedure if your guest count changes']},
 {heading:'Carry the agreed number into the booking',paragraphs:['The quote and confirmation should state the guest count or agreed capacity assumption. Ask whether changing it affects rental, room access, cleaning or other charges. Keep those conditions with the booking documents.','Guest capacities listed on RiteVenue are supplied by the venue. Confirm safe capacity for your event layout and any relevant venue permissions with the operator.']}
 ]}
];
