export type Venue={slug:string;name:string;city:string;area:string;type:string;occasions:string[];capacity:number;price:number;image:string;amenities:string[];description:string};
export const cities=['All Bengaluru','Bengaluru'];
export const occasions=['All occasions','Wedding','Reception','Birthday','Engagement','Corporate event'];
export const venueTypes=['All venues','Outdoor venue','Resort','Hotel','Party hall','Wedding hall'];
const sampleRows:[string,string,string,number,number][]=[
 ['The Jacaranda Lawn','Yelahanka','Outdoor venue',600,125000],['The Palace Courtyard','Vijayanagar','Wedding hall',800,180000],['Terrace & Twine','Indiranagar','Party hall',120,35000],['The Canopy Retreat','Kanakapura Road','Resort',350,140000],['The Atrium Hotel','Whitefield','Hotel',400,110000],['The Garden Room','Jayanagar','Party hall',80,22000],['Silverleaf Meadows','Devanahalli','Outdoor venue',700,155000],['The Marigold Pavilion','Rajajinagar','Wedding hall',1000,160000],['Azure Grove Resort','Bannerghatta Road','Resort',300,120000],['The Meridian Ballroom','Hebbal','Hotel',500,150000],['Juniper Social','Koramangala','Party hall',150,45000],['The Lotus Assembly','Basavanagudi','Wedding hall',650,95000],['Willow & Sky','Sarjapur Road','Outdoor venue',450,105000],['Cedarstone Retreat','Hesaraghatta','Resort',250,90000],['The Glasshouse Hotel','MG Road','Hotel',220,85000],['The Celebration Studio','HSR Layout','Party hall',100,30000],['Saffron Court','JP Nagar','Wedding hall',550,80000],['Moonflower Gardens','Jakkur','Outdoor venue',350,75000],['The Fernside Resort','Hoskote','Resort',400,130000],['The Crescent Hotel','Malleshwaram','Hotel',300,100000]
];
export const venues:Venue[]=sampleRows.map(([name,area,type,capacity,price])=>({slug:name.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-'),name,area,type,capacity,price,city:'Bengaluru',occasions:type==='Party hall'?['Birthday','Engagement','Corporate event']:['Wedding','Reception','Engagement','Corporate event'],image:type==='Outdoor venue'||type==='Resort'?'/images/lawn.jpg':type==='Party hall'?'/images/party.jpg':'/images/hall.jpg',amenities:['Parking','Bridal room',...(type==='Outdoor venue'||type==='Resort'?['Outdoor space','Covered backup area']:['Air conditioning','Dining area'])],description:type==='Outdoor venue'||type==='Resort'?'An open-air celebration setting with room for your ceremony and reception. Explore the full-day rental and covered backup option in this fictional owner-demo listing.':'A welcoming indoor setting for your celebration, with guest seating and a separate gathering area. All facilities, prices and availability in this listing are demonstration data.'}));
export const localities=['All Bengaluru',...venues.map(v=>v.area).sort()];
export function money(value:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(value);}
// Do not assume a locale's display format is an ISO date (browser ICU versions differ).
export function indiaToday(){const parts=new Intl.DateTimeFormat('en',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const value=(type:string)=>parts.find(p=>p.type===type)!.value;return `${value('year')}-${value('month')}-${value('day')}`;}
export type Filters={city:string;occasion:string;guests:number;budget:number;type:string;query:string;sort:string};
export function filterVenues(f:Filters){return venues.filter(v=>(f.city==='All Bengaluru'||f.city==='All Karnataka'||v.city===f.city)&&(f.occasion==='All occasions'||v.occasions.includes(f.occasion))&&v.capacity>=f.guests&&v.price<=f.budget&&(f.type==='All venues'||v.type===f.type)&&(!f.query||(v.name+' '+v.area).toLowerCase().includes(f.query.toLowerCase()))).sort((a,b)=>f.sort==='price-low'?a.price-b.price:f.sort==='capacity'?b.capacity-a.capacity:0);}
