import {notFound} from 'next/navigation';
import {publicVenue} from '@/lib/public-venues';
import {SITE_ORIGIN,publicIndexingEnabled} from '@/lib/launch';
import {money} from '@/lib/venues';
import {policyLabels} from '@/lib/catering';
import PublicCalendar from '@/components/public-calendar';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const v=await publicVenue(slug),index=publicIndexingEnabled();return v?{title:v.name+' in '+v.area+', Bengaluru',description:v.description.slice(0,155),alternates:{canonical:SITE_ORIGIN+'/venues/'+v.slug},robots:{index,follow:index}}:{title:'Venue not found',robots:{index:false,follow:false}};}
export default async function Venue({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const v=await publicVenue(slug);if(!v)notFound();return <main className="content-page"><nav className="breadcrumb"><a href="/">Venues</a><span>/</span><span>{v.area}</span></nav><div className="detail-title"><span className="tag">{v.type} · Owner-supplied listing</span><h1>{v.name}</h1><p>{v.area}, Bengaluru · Up to {v.capacity} guests</p></div><a className="primary" href="#availability">View calendar</a><img className="detail-photo" src={v.images[0]} alt={v.imageDescriptions[0]} width={1200} height={600}/><p className="photo-caption">Photographs supplied by the venue for public display.</p>{v.images.length>1&&<div className="venue-gallery">{v.images.slice(1).map((src,i)=><img src={src} key={src} alt={v.imageDescriptions[i+1]} width={600} height={400} loading="lazy"/>)}</div>}<h2>About the venue</h2><p className="prose">{v.description}</p><p><strong>Address:</strong> {v.address}</p><section className="public-prices"><h2>Rental information</h2><p>Owner-provided amounts, subject to confirmation. These are not a final quote or a price-lock guarantee.</p>{[['Standard Marriage · 4 PM to 4 PM next day',v.pricing.marriageRent],['Full Day · 8 AM to 10 PM',v.pricing.rent],['Morning · 7 AM to 2 PM',v.pricing.morningRent],['Evening · 4 PM to 11 PM',v.pricing.eveningRent],['Extended access · per hour',v.pricing.extraHour],['AC',v.pricing.ac],['Generator',v.pricing.generator],['Parking',v.pricing.parking],['Cleaning',v.pricing.cleaning]].map(([label,amount])=><div className="quote-line" key={String(label)}><span>{label}</span><strong>{Number(amount)===0?'Included':money(Number(amount)/100)}</strong></div>)}<p className="muted">Taxes, food, optional services and final terms must be confirmed with the venue. No online payment is collected.</p></section><section className="catering-policy"><div><h2>{policyLabels[v.cateringPolicy.mode]}</h2><p>{v.cateringPolicy.notes||'Ask the venue to confirm its food and outside-caterer rules.'}</p><p>Catering / kitchen fee: {money(v.cateringPolicy.venueFee/100)} · Minimum food spend: {money(v.cateringPolicy.minimumFoodSpend/100)}. Catering booking is not offered during this launch.</p></div></section><PublicCalendar slug={v.slug} initialCalendar={v.calendar} initialUpdatedAt={v.calendarUpdatedAt||''}/></main>;}
