import {notFound} from 'next/navigation';
import Link from 'next/link';
import {MapPin,Users,Check,ShieldCheck} from 'lucide-react';
import {venues,indiaToday} from '@/lib/venues';
import {dateSchema,validDate,lastBookableDate} from '@/lib/booking';
import {calendarSnapshot} from '@/lib/calendar';
import {venuePricing} from '@/lib/demo-server';
import {requireChatGPTUser} from '@/app/chatgpt-auth';
import BookingPanel from '@/components/booking-panel';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const v=venues.find(v=>v.slug===slug);return {title:v?`${v.name} | Fictional venue demo`:'Venue not found',description:'Private RiteVenue demonstration. Fictional venue, illustrative photos and simulated bookings.',robots:{index:false,follow:false}};}
export default async function VenuePage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{date?:string;guests?:string;month?:string;checkoutError?:string}>}){const {slug}=await params;const search=await searchParams;if(!venues.some(v=>v.slug===slug))notFound();return <ProtectedVenue slug={slug} date={dateSchema.safeParse(search.date).success?search.date!:''} guests={Number(search.guests)||1} month={search.month||''} checkoutError={!!search.checkoutError}/>;}
async function ProtectedVenue({slug,date,guests,month,checkoutError}:{slug:string;date:string;guests:number;month:string;checkoutError:boolean}){const user=await requireChatGPTUser('/venues/'+slug);const today=indiaToday();const selectedMonth=/^\d{4}-\d{2}$/.test(month)&&validDate(month+'-01')&&month>=today.slice(0,7)&&month<=lastBookableDate().slice(0,7)?month:(date||today).slice(0,7);let data;let calendar;try{data=await venuePricing(slug);calendar=await calendarSnapshot(slug,selectedMonth,user.userId);}catch{return <main className="content-page"><h1>Venue availability is temporarily unavailable</h1><p>Please refresh before starting a demo booking.</p></main>;}const {venue:v,pricing}=data;return <main className="content-page"><div className="breadcrumb"><Link href="/">Explore venues</Link><span>/</span><span>{v.area}</span><span>/</span><span>{v.name}</span></div><div className="detail-title"><span className="tag">{v.type} · Fictional demo venue</span><h1>{v.name}</h1><p><MapPin size={17}/>{v.area}, Bengaluru <span>·</span><Users size={17}/>Up to {v.capacity} guests</p></div><a className="primary" href="#book">View dates & book this demo venue</a><img className="detail-photo" src={v.image} alt="Illustrative event setting, not a photograph of a real RiteVenue partner" width="1200" height="600"/><p className="photo-caption">Sample venue name, real locality. Photos, facilities, prices and date inventory are illustrative.</p><div className="venue-summary"><div><h2>A space for your celebration</h2><p>{v.description}</p><ul className="amenities">{v.amenities.map(a=><li key={a}><Check size={17}/>{a}</li>)}</ul></div><div className="trust-summary"><ShieldCheck size={26}/><h2>Your date. Your price.</h2><p>Pick a date, see every charge and confirm without a callback. Try the complete self-serve flow below.</p><p className="muted">Demo only. A real price-lock guarantee requires venue agreements and approved booking terms.</p></div></div><BookingPanel venue={v} pricing={pricing} initialDate={date} initialGuests={Number.isFinite(guests)?Math.floor(guests):1} initialCalendar={calendar} today={today} checkoutError={checkoutError}/><section className="review-section"><h2>Verified booking reviews</h2><p>No verified reviews yet. Fictional venues and simulated bookings do not generate ratings.</p></section></main>;}
